


WITH unionized_data AS (
         SELECT DISTINCT ddiml.id AS id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (ddiml.date)::date AS date,
            ddiml.influencer_name,
            ddiml.campaign,
            ddiml.engagement::text,
            ddiml.voucher AS coupon_code,
            ddiml.e_nr::double precision AS estimated_net_revenue,
            ddiml.total_costs::double precision,
            ddiml.follower AS gross_reach,
            ddiml.r_views,
            ddiml.campaign_status,
            ddiml.size,
            ddiml.category,
            ddiml.medium,
            ddiml.medium_type,
            ddiml.content,
            ddiml.quality,
            ddiml.reporting_shared,
            ddiml.project_management,
            ddiml._fivetran_synced,
            (ddiml.id::text || ''::text) || ddiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_dach"."influencer_manual_upload" ddiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON ddiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(ddiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
        UNION ALL
         SELECT DISTINCT dfiml.id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (dfiml.date)::date AS date,
            dfiml.influencer_name,
            dfiml.campaign,
            dfiml.engagement::text,
            dfiml.voucher AS coupon_code,
            dfiml.e_nr::double precision AS estimated_net_revenue,
            dfiml.total_costs::double precision,
            dfiml.follower AS gross_reach,
            dfiml.r_views,
            dfiml.campaign_status,
            dfiml.size,
            dfiml.category,
            dfiml.medium,
            dfiml.medium_type,
            dfiml.content,
            dfiml.quality,
            dfiml.reporting_shared,
            dfiml.project_management,
            dfiml._fivetran_synced,
            (dfiml.id::text || ''::text) || dfiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_fr"."influencer_manual_upload" dfiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON dfiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(dfiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
        UNION ALL
         SELECT DISTINCT dbiml.id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (dbiml.date)::date AS date,
            dbiml.influencer_name,
            dbiml.campaign,
            dbiml.engagement::text,
            dbiml.voucher AS coupon_code,
            dbiml.e_nr::double precision AS estimated_net_revenue,
            dbiml.total_costs::double precision,
            dbiml.follower AS gross_reach,
            dbiml.r_views,
            dbiml.campaign_status,
            dbiml.size,
            dbiml.category,
            dbiml.medium,
            dbiml.medium_type,
            dbiml.content,
            dbiml.quality,
            dbiml.reporting_shared,
            dbiml.project_management,
            dbiml._fivetran_synced,
            (dbiml.id::text || ''::text) || dbiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_benelux"."influencer_manual_upload" dbiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON dbiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(dbiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
        union all
        	SELECT DISTINCT diiml.id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (diiml.date)::date AS date,
            diiml.influencer_name,
            diiml.campaign,
            diiml.engagement::text,
            diiml.voucher AS coupon_code,
            diiml.e_nr::double precision AS estimated_net_revenue,
            diiml.total_costs::double precision,
            diiml.follower AS gross_reach,
            diiml.r_views,
            diiml.campaign_status,
            diiml.size,
            diiml.category,
            diiml.medium,
            diiml.medium_type,
            diiml.content,
            diiml.quality,
            diiml.reporting_shared,
            diiml.project_management,
            diiml._fivetran_synced,
            (diiml.id::text || ''::text) || diiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_it"."influencer_manual_upload" diiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON diiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(diiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
        union all
        	SELECT DISTINCT duiml.id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (duiml.date)::date AS date,
            duiml.influencer_name,
            duiml.campaign,
            duiml.engagement::text,
            duiml.voucher AS coupon_code,
            duiml.e_nr::double precision AS estimated_net_revenue,
            duiml.total_costs::double precision,
            duiml.follower AS gross_reach,
            duiml.r_views:: double precision,
            duiml.campaign_status,
            duiml.size,
            duiml.category,
            duiml.medium,
            duiml.medium_type,
            duiml.content,
            duiml.quality,
            duiml.reporting_shared,
            duiml.project_management,
            duiml._fivetran_synced,
            (duiml.id::text || ''::text) || duiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_uk"."influencer_manual_upload" duiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON duiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(duiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
        union all
            SELECT DISTINCT dsiml.id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (dsiml.date)::date AS date,
            dsiml.influencer_name,
            dsiml.campaign,
            dsiml.engagement::text AS engagement, 
            dsiml.voucher AS coupon_code,
            dsiml.e_nr::double precision AS estimated_net_revenue, 
            dsiml.total_costs::double precision,
            dsiml.follower AS gross_reach,
            dsiml.r_views AS r_views, 
            dsiml.campaign_status,
            dsiml.size,
            dsiml.category,
            dsiml.medium,
            dsiml.medium_type,
            dsiml.content as "content", 
            dsiml.quality as quality,  
            dsiml.reporting_shared as reporting_shared,
            dsiml.project_management,
            dsiml._fivetran_synced,
            (dsiml.id::text || ''::text) || dsiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_se"."influencer_manual_upload" dsiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON dsiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(dsiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
                union all
            SELECT DISTINCT dsiml.id,
            country_system_account_mapping.country_abbreviation,
            country_system_account_mapping.country_fullname,
            country_system_account_mapping.country_grouping,
            (dsiml.date)::date AS date,
            dsiml.influencer_name,
            dsiml.campaign,
            dsiml.engagement::text AS engagement, 
            dsiml.voucher AS coupon_code,
            0::double precision AS estimated_net_revenue, 
            dsiml.total_costs::double precision,
            dsiml.follower AS gross_reach,
            dsiml.r_views AS r_views, 
            dsiml.campaign_status,
            dsiml.size,
            dsiml.category,
            dsiml.medium,
            dsiml.medium_type,
            NULL AS "content", 
            NULL AS quality,  
            NULL AS reporting_shared,
            dsiml.project_management,
            dsiml._fivetran_synced,
            (dsiml.id::text || ''::text) || dsiml.voucher::text AS pk_voucher
           FROM "airup_eu_dwh"."influencer_us"."influencer_manual_upload" dsiml
             LEFT JOIN "airup_eu_dwh"."public"."country_system_account_mapping" country_system_account_mapping ON dsiml.country::text = country_system_account_mapping.country_abbreviation::text
        --   WHERE is_date(regexp_replace(dsiml.date::text, '\.0'::text, ''::text, 'g'::text)::character varying)
        )
 SELECT unionized_data.id,
    unionized_data.country_abbreviation AS country_shortname,
    unionized_data.country_fullname AS country,
    unionized_data.country_grouping AS region,
    unionized_data.date,
    unionized_data.influencer_name,
    unionized_data.campaign,
    unionized_data.engagement,
    unionized_data.coupon_code,
    unionized_data.estimated_net_revenue,
    unionized_data.total_costs,
    unionized_data.gross_reach,
    unionized_data.r_views,
    unionized_data.campaign_status,
    unionized_data.size,
    unionized_data.category,
    unionized_data.medium,
    unionized_data.medium_type,
    unionized_data.content,
    unionized_data.quality,
    unionized_data.reporting_shared,
    unionized_data.project_management,
    unionized_data._fivetran_synced,
    unionized_data.pk_voucher
   FROM unionized_data