

WITH airup_gmbh_sales_raw AS (
         SELECT airup_gmbh_sales._fivetran_synced,
            date(airup_gmbh_sales._fivetran_synced) AS creation_date,
            md5(airup_gmbh_sales.customer_email::text) AS customer_id,
            airup_gmbh_sales.day AS created_at,
            airup_gmbh_sales.utm_campaign_medium,
            airup_gmbh_sales.utm_campaign_name,
            airup_gmbh_sales.net_sales,
            NULL::double precision AS net_sales_chf,
            NULL::double precision AS net_sales_gbp,
            NULL::double precision AS net_sales_sek,
            airup_gmbh_sales.gross_sales,
            NULL::double precision AS gross_sales_chf,
            NULL::double precision AS gross_sales_gbp,
            NULL::double precision AS gross_sales_sek,
            airup_gmbh_sales.taxes,
            NULL::double precision AS taxes_chf,
            NULL::double precision AS taxes_gbp,
            NULL::double precision AS taxes_sek,
            airup_gmbh_sales.discounts,
            NULL::double precision AS discounts_chf,
            NULL::double precision AS discounts_gbp,
            NULL::double precision AS discounts_sek,
            airup_gmbh_sales.shipping,
            NULL::double precision AS shipping_chf,
            NULL::double precision AS shipping_gbp,
            NULL::double precision AS shipping_sek,
            airup_gmbh_sales.orders,
            airup_gmbh_sales.returns AS return_amount,
            NULL::double precision AS return_amount_chf,
            NULL::double precision AS return_amount_gbp,
            NULL::double precision AS return_amount_sek,
            'Base'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_gmbh_sales.customer_email,
            airup_gmbh_sales.customer_name,
            airup_gmbh_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_gmbh_sales" airup_gmbh_sales
        ), global_curr_eur AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'EUR'::text
        ), airup_gmbh_sales_curr AS (
         SELECT airup_gmbh_sales_raw._fivetran_synced,
            airup_gmbh_sales_raw.creation_date,
            airup_gmbh_sales_raw.customer_id,
            airup_gmbh_sales_raw.created_at,
            airup_gmbh_sales_raw.utm_campaign_medium,
            airup_gmbh_sales_raw.utm_campaign_name,
            airup_gmbh_sales_raw.net_sales,
            airup_gmbh_sales_raw.net_sales_chf,
            airup_gmbh_sales_raw.net_sales_gbp,
            airup_gmbh_sales_raw.net_sales_sek,
            airup_gmbh_sales_raw.gross_sales,
            airup_gmbh_sales_raw.gross_sales_chf,
            airup_gmbh_sales_raw.gross_sales_gbp,
            airup_gmbh_sales_raw.gross_sales_sek,
            airup_gmbh_sales_raw.taxes,
            airup_gmbh_sales_raw.taxes_chf,
            airup_gmbh_sales_raw.taxes_gbp,
            airup_gmbh_sales_raw.taxes_sek,
            airup_gmbh_sales_raw.discounts,
            airup_gmbh_sales_raw.discounts_chf,
            airup_gmbh_sales_raw.discounts_gbp,
            airup_gmbh_sales_raw.discounts_sek,
            airup_gmbh_sales_raw.shipping,
            airup_gmbh_sales_raw.shipping_chf,
            airup_gmbh_sales_raw.shipping_gbp,
            airup_gmbh_sales_raw.shipping_sek,
            airup_gmbh_sales_raw.orders,
            airup_gmbh_sales_raw.return_amount,
            airup_gmbh_sales_raw.return_amount_chf,
            airup_gmbh_sales_raw.return_amount_gbp,
            airup_gmbh_sales_raw.return_amount_sek,
            airup_gmbh_sales_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_gmbh_sales_raw.customer_email,
            airup_gmbh_sales_raw.customer_name,
            airup_gmbh_sales_raw.shop_cust_id
           FROM airup_gmbh_sales_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_ch_sales_raw AS (
         SELECT airup_ch_sales._fivetran_synced,
            date(airup_ch_sales._fivetran_synced) AS creation_date,
            md5(airup_ch_sales.customer_email::text) AS customer_id,
            airup_ch_sales.day AS created_at,
            airup_ch_sales.utm_campaign_medium,
            airup_ch_sales.utm_campaign_name,
            airup_ch_sales.net_sales,
            airup_ch_sales.net_sales AS net_sales_chf,
            NULL::double precision AS net_sales_gbp,
            NULL::double precision AS net_sales_sek,
            airup_ch_sales.gross_sales,
            airup_ch_sales.gross_sales AS gross_sales_chf,
            NULL::double precision AS gross_sales_gbp,
            NULL::double precision AS gross_sales_sek,
            airup_ch_sales.taxes,
            airup_ch_sales.taxes AS taxes_chf,
            NULL::double precision AS taxes_gbp,
            NULL::double precision AS taxes_sek,
            airup_ch_sales.discounts,
            airup_ch_sales.discounts AS discounts_chf,
            NULL::double precision AS discounts_gbp,
            NULL::double precision AS discounts_sek,
            airup_ch_sales.shipping,
            airup_ch_sales.shipping AS shipping_chf,
            NULL::double precision AS shipping_gbp,
            NULL::double precision AS shipping_sek,
            airup_ch_sales.orders,
            airup_ch_sales.returns AS return_amount,
            airup_ch_sales.returns AS return_amount_chf,
            NULL::double precision AS return_amount_gbp,
            NULL::double precision AS return_amount_sek,
            'CH'::text AS shopify_shop,
            'CHF'::text AS currency_abbreviation,
            airup_ch_sales.customer_email,
            airup_ch_sales.customer_name,
            airup_ch_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_ch_sales" airup_ch_sales
        ), global_curr_chf AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'CHF'::text
        ), airup_ch_sales_curr AS (
         SELECT airup_ch_sales_raw._fivetran_synced,
            airup_ch_sales_raw.creation_date,
            airup_ch_sales_raw.customer_id,
            airup_ch_sales_raw.created_at,
            airup_ch_sales_raw.utm_campaign_medium,
            airup_ch_sales_raw.utm_campaign_name,
            (airup_ch_sales_raw.net_sales /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS net_sales,
            airup_ch_sales_raw.net_sales_chf,
            airup_ch_sales_raw.net_sales_gbp,
            airup_ch_sales_raw.net_sales_sek,
            (airup_ch_sales_raw.gross_sales /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS gross_sales,
            airup_ch_sales_raw.gross_sales_chf,
            airup_ch_sales_raw.gross_sales_gbp,
            airup_ch_sales_raw.gross_sales_sek,
            (airup_ch_sales_raw.taxes /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS taxes,
            airup_ch_sales_raw.taxes_chf,
            airup_ch_sales_raw.taxes_gbp,
            airup_ch_sales_raw.taxes_sek,
            (airup_ch_sales_raw.discounts /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS discounts,
            airup_ch_sales_raw.discounts_chf,
            airup_ch_sales_raw.discounts_gbp,
            airup_ch_sales_raw.discounts_sek,
            (airup_ch_sales_raw.shipping /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS shipping,
            airup_ch_sales_raw.shipping_chf,
            airup_ch_sales_raw.shipping_gbp,
            airup_ch_sales_raw.shipping_sek,
            airup_ch_sales_raw.orders,
            (airup_ch_sales_raw.return_amount /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS return_amount,
            airup_ch_sales_raw.return_amount_chf,
            airup_ch_sales_raw.return_amount_gbp,
            airup_ch_sales_raw.return_amount_sek,
            airup_ch_sales_raw.shopify_shop,
            global_curr_chf.currency_abbreviation,
            global_curr_chf.conversion_rate_eur,
            airup_ch_sales_raw.customer_email,
            airup_ch_sales_raw.customer_name,
            airup_ch_sales_raw.shop_cust_id
           FROM airup_ch_sales_raw
             LEFT JOIN global_curr_chf USING (currency_abbreviation, creation_date)
        ), airup_uk_sales_raw AS (
         SELECT airup_uk_sales._fivetran_synced,
            date(airup_uk_sales._fivetran_synced) AS creation_date,
            md5(airup_uk_sales.customer_email::text) AS customer_id,
            airup_uk_sales.day AS created_at,
            airup_uk_sales.utm_campaign_medium,
            airup_uk_sales.utm_campaign_name,
            airup_uk_sales.net_sales,
            NULL::double precision AS net_sales_chf,
            airup_uk_sales.net_sales AS net_sales_gbp,
            NULL::double precision AS net_sales_sek,
            airup_uk_sales.gross_sales,
            NULL::double precision AS gross_sales_chf,
            airup_uk_sales.gross_sales AS gross_sales_gbp,
            NULL::double precision AS gross_sales_sek,
            airup_uk_sales.taxes,
            NULL::double precision AS taxes_chf,
            airup_uk_sales.taxes AS taxes_gbp,
            NULL::double precision AS taxes_sek,
            airup_uk_sales.discounts,
            NULL::double precision AS discounts_chf,
            airup_uk_sales.discounts AS discounts_gbp,
            NULL::double precision AS discounts_sek,
            airup_uk_sales.shipping,
            NULL::double precision AS shipping_chf,
            airup_uk_sales.shipping AS shipping_gbp,
            NULL::double precision AS shipping_sek,
            airup_uk_sales.orders,
            airup_uk_sales.returns AS return_amount,
            NULL::double precision AS return_amount_chf,
            airup_uk_sales.returns AS return_amount_gbp,
            NULL::double precision AS return_amount_sek,
            'UK'::text AS shopify_shop,
            'GBP'::text AS currency_abbreviation,
            airup_uk_sales.customer_email,
            airup_uk_sales.customer_name,
            airup_uk_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_uk_sales" airup_uk_sales
        ), global_curr_gbp AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'GBP'::text
        ), airup_uk_sales_curr AS (
         SELECT airup_uk_sales_raw._fivetran_synced,
            airup_uk_sales_raw.creation_date,
            airup_uk_sales_raw.customer_id,
            airup_uk_sales_raw.created_at,
            airup_uk_sales_raw.utm_campaign_medium,
            airup_uk_sales_raw.utm_campaign_name,
            (airup_uk_sales_raw.net_sales /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS net_sales,
            airup_uk_sales_raw.net_sales_chf,
            airup_uk_sales_raw.net_sales_gbp,
            airup_uk_sales_raw.net_sales_sek,
            (airup_uk_sales_raw.gross_sales /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS gross_sales,
            airup_uk_sales_raw.gross_sales_chf,
            airup_uk_sales_raw.gross_sales_gbp,
            airup_uk_sales_raw.gross_sales_sek,
            (airup_uk_sales_raw.taxes /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS taxes,
            airup_uk_sales_raw.taxes_chf,
            airup_uk_sales_raw.taxes_gbp,
            airup_uk_sales_raw.taxes_sek,
            (airup_uk_sales_raw.discounts /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS discounts,
            airup_uk_sales_raw.discounts_chf,
            airup_uk_sales_raw.discounts_gbp,
            airup_uk_sales_raw.discounts_sek,
            (airup_uk_sales_raw.shipping /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS shipping,
            airup_uk_sales_raw.shipping_chf,
            airup_uk_sales_raw.shipping_gbp,
            airup_uk_sales_raw.shipping_sek,
            airup_uk_sales_raw.orders,
            (airup_uk_sales_raw.return_amount /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS return_amount,
            airup_uk_sales_raw.return_amount_chf,
            airup_uk_sales_raw.return_amount_gbp,
            airup_uk_sales_raw.return_amount_sek,
            airup_uk_sales_raw.shopify_shop,
            global_curr_gbp.currency_abbreviation,
            global_curr_gbp.conversion_rate_eur,
            airup_uk_sales_raw.customer_email,
            airup_uk_sales_raw.customer_name,
            airup_uk_sales_raw.shop_cust_id
           FROM airup_uk_sales_raw
             LEFT JOIN global_curr_gbp USING (currency_abbreviation, creation_date)
        ), airup_fr_sales_raw AS (
         SELECT airup_fr_sales._fivetran_synced,
            date(airup_fr_sales._fivetran_synced) AS creation_date,
            md5(airup_fr_sales.customer_email::text) AS customer_id,
            airup_fr_sales.day AS created_at,
            airup_fr_sales.utm_campaign_medium,
            airup_fr_sales.utm_campaign_name,
            airup_fr_sales.net_sales,
            NULL::double precision AS net_sales_chf,
            NULL::double precision AS net_sales_gbp,
            NULL::double precision AS net_sales_sek,
            airup_fr_sales.gross_sales,
            NULL::double precision AS gross_sales_chf,
            NULL::double precision AS gross_sales_gbp,
            NULL::double precision AS gross_sales_sek,
            airup_fr_sales.taxes,
            NULL::double precision AS taxes_chf,
            NULL::double precision AS taxes_gbp,
            NULL::double precision AS taxes_sek,
            airup_fr_sales.discounts,
            NULL::double precision AS discounts_chf,
            NULL::double precision AS discounts_gbp,
            NULL::double precision AS discounts_sek,
            airup_fr_sales.shipping,
            NULL::double precision AS shipping_chf,
            NULL::double precision AS shipping_gbp,
            NULL::double precision AS shipping_sek,
            airup_fr_sales.orders,
            airup_fr_sales.returns AS return_amount,
            NULL::double precision AS return_amount_chf,
            NULL::double precision AS return_amount_gbp,
            NULL::double precision AS return_amount_sek,
            'FR'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_fr_sales.customer_email,
            airup_fr_sales.customer_name,
            airup_fr_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_fr_sales" airup_fr_sales
        ), airup_fr_sales_curr AS (
         SELECT airup_fr_sales_raw._fivetran_synced,
            airup_fr_sales_raw.creation_date,
            airup_fr_sales_raw.customer_id,
            airup_fr_sales_raw.created_at,
            airup_fr_sales_raw.utm_campaign_medium,
            airup_fr_sales_raw.utm_campaign_name,
            airup_fr_sales_raw.net_sales,
            airup_fr_sales_raw.net_sales_chf,
            airup_fr_sales_raw.net_sales_gbp,
            airup_fr_sales_raw.net_sales_sek,
            airup_fr_sales_raw.gross_sales,
            airup_fr_sales_raw.gross_sales_chf,
            airup_fr_sales_raw.gross_sales_gbp,
            airup_fr_sales_raw.gross_sales_sek,
            airup_fr_sales_raw.taxes,
            airup_fr_sales_raw.taxes_chf,
            airup_fr_sales_raw.taxes_gbp,
            airup_fr_sales_raw.taxes_sek,
            airup_fr_sales_raw.discounts,
            airup_fr_sales_raw.discounts_chf,
            airup_fr_sales_raw.discounts_gbp,
            airup_fr_sales_raw.discounts_sek,
            airup_fr_sales_raw.shipping,
            airup_fr_sales_raw.shipping_chf,
            airup_fr_sales_raw.shipping_gbp,
            airup_fr_sales_raw.shipping_sek,
            airup_fr_sales_raw.orders,
            airup_fr_sales_raw.return_amount,
            airup_fr_sales_raw.return_amount_chf,
            airup_fr_sales_raw.return_amount_gbp,
            airup_fr_sales_raw.return_amount_sek,
            airup_fr_sales_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_fr_sales_raw.customer_email,
            airup_fr_sales_raw.customer_name,
            airup_fr_sales_raw.shop_cust_id
           FROM airup_fr_sales_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_nl_sales_raw AS (
         SELECT airup_nl_sales._fivetran_synced,
            date(airup_nl_sales._fivetran_synced) AS creation_date,
            md5(airup_nl_sales.customer_email::text) AS customer_id,
            airup_nl_sales.day AS created_at,
            airup_nl_sales.utm_campaign_medium,
            airup_nl_sales.utm_campaign_name,
            airup_nl_sales.net_sales,
            NULL::double precision AS net_sales_chf,
            NULL::double precision AS net_sales_gbp,
            NULL::double precision AS net_sales_sek,
            airup_nl_sales.gross_sales,
            NULL::double precision AS gross_sales_chf,
            NULL::double precision AS gross_sales_gbp,
            NULL::double precision AS gross_sales_sek,
            airup_nl_sales.taxes,
            NULL::double precision AS taxes_chf,
            NULL::double precision AS taxes_gbp,
            NULL::double precision AS taxes_sek,
            airup_nl_sales.discounts,
            NULL::double precision AS discounts_chf,
            NULL::double precision AS discounts_gbp,
            NULL::double precision AS discounts_sek,
            airup_nl_sales.shipping,
            NULL::double precision AS shipping_chf,
            NULL::double precision AS shipping_gbp,
            NULL::double precision AS shipping_sek,
            airup_nl_sales.orders,
            airup_nl_sales.returns AS return_amount,
            NULL::double precision AS return_amount_chf,
            NULL::double precision AS return_amount_gbp,
            NULL::double precision AS return_amount_sek,
            'NL'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_nl_sales.customer_email,
            airup_nl_sales.customer_name,
            airup_nl_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_nl_sales" airup_nl_sales
        ), airup_nl_sales_curr AS (
         SELECT airup_nl_sales_raw._fivetran_synced,
            airup_nl_sales_raw.creation_date,
            airup_nl_sales_raw.customer_id,
            airup_nl_sales_raw.created_at,
            airup_nl_sales_raw.utm_campaign_medium,
            airup_nl_sales_raw.utm_campaign_name,
            airup_nl_sales_raw.net_sales,
            airup_nl_sales_raw.net_sales_chf,
            airup_nl_sales_raw.net_sales_gbp,
            airup_nl_sales_raw.net_sales_sek,
            airup_nl_sales_raw.gross_sales,
            airup_nl_sales_raw.gross_sales_chf,
            airup_nl_sales_raw.gross_sales_gbp,
            airup_nl_sales_raw.gross_sales_sek,
            airup_nl_sales_raw.taxes,
            airup_nl_sales_raw.taxes_chf,
            airup_nl_sales_raw.taxes_gbp,
            airup_nl_sales_raw.taxes_sek,
            airup_nl_sales_raw.discounts,
            airup_nl_sales_raw.discounts_chf,
            airup_nl_sales_raw.discounts_gbp,
            airup_nl_sales_raw.discounts_sek,
            airup_nl_sales_raw.shipping,
            airup_nl_sales_raw.shipping_chf,
            airup_nl_sales_raw.shipping_gbp,
            airup_nl_sales_raw.shipping_sek,
            airup_nl_sales_raw.orders,
            airup_nl_sales_raw.return_amount,
            airup_nl_sales_raw.return_amount_chf,
            airup_nl_sales_raw.return_amount_gbp,
            airup_nl_sales_raw.return_amount_sek,
            airup_nl_sales_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_nl_sales_raw.customer_email,
            airup_nl_sales_raw.customer_name,
            airup_nl_sales_raw.shop_cust_id
           FROM airup_nl_sales_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_it_sales_raw AS (
         SELECT airup_it_sales._fivetran_synced,
            date(airup_it_sales._fivetran_synced) AS creation_date,
            md5(airup_it_sales.customer_email::text) AS customer_id,
            airup_it_sales.day AS created_at,
            airup_it_sales.utm_campaign_medium,
            airup_it_sales.utm_campaign_name,
            airup_it_sales.net_sales,
            NULL::double precision AS net_sales_chf,
            NULL::double precision AS net_sales_gbp,
            NULL::double precision AS net_sales_sek,
            airup_it_sales.gross_sales,
            NULL::double precision AS gross_sales_chf,
            NULL::double precision AS gross_sales_gbp,
            NULL::double precision AS gross_sales_sek,
            airup_it_sales.taxes,
            NULL::double precision AS taxes_chf,
            NULL::double precision AS taxes_gbp,
            NULL::double precision AS taxes_sek,
            airup_it_sales.discounts,
            NULL::double precision AS discounts_chf,
            NULL::double precision AS discounts_gbp,
            NULL::double precision AS discounts_sek,
            airup_it_sales.shipping,
            NULL::double precision AS shipping_chf,
            NULL::double precision AS shipping_gbp,
            NULL::double precision AS shipping_sek,
            airup_it_sales.orders,
            airup_it_sales.returns AS return_amount,
            NULL::double precision AS return_amount_chf,
            NULL::double precision AS return_amount_gbp,
            NULL::double precision AS return_amount_sek,
            'IT'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_it_sales.customer_email,
            airup_it_sales.customer_name,
            airup_it_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_it_sales" airup_it_sales
        ), airup_it_sales_curr AS (
         SELECT airup_it_sales_raw._fivetran_synced,
            airup_it_sales_raw.creation_date,
            airup_it_sales_raw.customer_id,
            airup_it_sales_raw.created_at,
            airup_it_sales_raw.utm_campaign_medium,
            airup_it_sales_raw.utm_campaign_name,
            airup_it_sales_raw.net_sales,
            airup_it_sales_raw.net_sales_chf,
            airup_it_sales_raw.net_sales_gbp,
            airup_it_sales_raw.net_sales_sek,
            airup_it_sales_raw.gross_sales,
            airup_it_sales_raw.gross_sales_chf,
            airup_it_sales_raw.gross_sales_gbp,
            airup_it_sales_raw.gross_sales_sek,
            airup_it_sales_raw.taxes,
            airup_it_sales_raw.taxes_chf,
            airup_it_sales_raw.taxes_gbp,
            airup_it_sales_raw.taxes_sek,
            airup_it_sales_raw.discounts,
            airup_it_sales_raw.discounts_chf,
            airup_it_sales_raw.discounts_gbp,
            airup_it_sales_raw.discounts_sek,
            airup_it_sales_raw.shipping,
            airup_it_sales_raw.shipping_chf,
            airup_it_sales_raw.shipping_gbp,
            airup_it_sales_raw.shipping_sek,
            airup_it_sales_raw.orders,
            airup_it_sales_raw.return_amount,
            airup_it_sales_raw.return_amount_chf,
            airup_it_sales_raw.return_amount_gbp,
            airup_it_sales_raw.return_amount_sek,
            airup_it_sales_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_it_sales_raw.customer_email,
            airup_it_sales_raw.customer_name,
            airup_it_sales_raw.shop_cust_id
           FROM airup_it_sales_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_sek_sales_raw AS (
         SELECT airup_sek_sales._fivetran_synced,
            date(airup_sek_sales._fivetran_synced) AS creation_date,
            md5(airup_sek_sales.customer_email::text) AS customer_id,
            airup_sek_sales.day AS created_at,
            airup_sek_sales.utm_campaign_medium,
            airup_sek_sales.utm_campaign_name,
            airup_sek_sales.net_sales,
            NULL::double precision AS net_sales_chf,
            NULL::double precision AS net_sales_gbp,
            airup_sek_sales.net_sales AS net_sales_sek,
            airup_sek_sales.gross_sales,
            NULL::double precision AS gross_sales_chf,
            NULL::double precision AS gross_sales_gbp,
            airup_sek_sales.gross_sales AS gross_sales_sek,
            airup_sek_sales.taxes,
            NULL::double precision AS taxes_chf,
            NULL::double precision AS taxes_gbp,
            airup_sek_sales.taxes AS taxes_sek,
            airup_sek_sales.discounts,
            NULL::double precision AS discounts_chf,
            NULL::double precision AS discounts_gbp,
            airup_sek_sales.discounts AS discounts_sek,
            airup_sek_sales.shipping,
            NULL::double precision AS shipping_chf,
            NULL::double precision AS shipping_gbp,
            airup_sek_sales.shipping AS shipping_sek,
            airup_sek_sales.orders,
            airup_sek_sales.returns AS return_amount,
            NULL::double precision AS return_amount_chf,
            NULL::double precision AS return_amount_gbp,
            airup_sek_sales.returns AS return_amount_sek,
            'SE'::text AS shopify_shop,
            'SEK'::text AS currency_abbreviation,
            airup_sek_sales.customer_email,
            airup_sek_sales.customer_name,
            airup_sek_sales.customer_id AS shop_cust_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_se_sales" airup_sek_sales
        ), global_curr_sek AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'SEK'::text
        ), airup_sek_sales_curr AS (
         SELECT airup_sek_sales_raw._fivetran_synced,
            airup_sek_sales_raw.creation_date,
            airup_sek_sales_raw.customer_id,
            airup_sek_sales_raw.created_at,
            airup_sek_sales_raw.utm_campaign_medium,
            airup_sek_sales_raw.utm_campaign_name,
            (airup_sek_sales_raw.net_sales /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS net_sales,
            airup_sek_sales_raw.net_sales_chf,
            airup_sek_sales_raw.net_sales_gbp,
            airup_sek_sales_raw.net_sales_sek,
            (airup_sek_sales_raw.gross_sales /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS gross_sales,
            airup_sek_sales_raw.gross_sales_chf,
            airup_sek_sales_raw.gross_sales_gbp,
            airup_sek_sales_raw.gross_sales_sek,
            (airup_sek_sales_raw.taxes /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS taxes,
            airup_sek_sales_raw.taxes_chf,
            airup_sek_sales_raw.taxes_gbp,
            airup_sek_sales_raw.taxes_sek,
            (airup_sek_sales_raw.discounts /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS discounts,
            airup_sek_sales_raw.discounts_chf,
            airup_sek_sales_raw.discounts_gbp,
            airup_sek_sales_raw.discounts_sek,
            (airup_sek_sales_raw.shipping /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS shipping,
            airup_sek_sales_raw.shipping_chf,
            airup_sek_sales_raw.shipping_gbp,
            airup_sek_sales_raw.shipping_sek,
            airup_sek_sales_raw.orders,
            (airup_sek_sales_raw.return_amount /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS return_amount,
            airup_sek_sales_raw.return_amount_chf,
            airup_sek_sales_raw.return_amount_gbp,
            airup_sek_sales_raw.return_amount_sek,
            airup_sek_sales_raw.shopify_shop,
            global_curr_sek.currency_abbreviation,
            global_curr_sek.conversion_rate_eur,
            airup_sek_sales_raw.customer_email,
            airup_sek_sales_raw.customer_name,
            airup_sek_sales_raw.shop_cust_id
           FROM airup_sek_sales_raw
             LEFT JOIN global_curr_sek USING (currency_abbreviation, creation_date)
        )
 SELECT airup_gmbh_sales_curr._fivetran_synced,
    airup_gmbh_sales_curr.creation_date,
    airup_gmbh_sales_curr.customer_id,
    airup_gmbh_sales_curr.created_at,
    airup_gmbh_sales_curr.utm_campaign_medium,
    airup_gmbh_sales_curr.utm_campaign_name,
    airup_gmbh_sales_curr.net_sales,
    airup_gmbh_sales_curr.net_sales_chf,
    airup_gmbh_sales_curr.net_sales_gbp,
    airup_gmbh_sales_curr.net_sales_sek,
    airup_gmbh_sales_curr.gross_sales,
    airup_gmbh_sales_curr.gross_sales_chf,
    airup_gmbh_sales_curr.gross_sales_gbp,
    airup_gmbh_sales_curr.gross_sales_sek,
    airup_gmbh_sales_curr.taxes,
    airup_gmbh_sales_curr.taxes_chf,
    airup_gmbh_sales_curr.taxes_gbp,
    airup_gmbh_sales_curr.taxes_sek,
    airup_gmbh_sales_curr.discounts,
    airup_gmbh_sales_curr.discounts_chf,
    airup_gmbh_sales_curr.discounts_gbp,
    airup_gmbh_sales_curr.discounts_sek,
    airup_gmbh_sales_curr.shipping,
    airup_gmbh_sales_curr.shipping_chf,
    airup_gmbh_sales_curr.shipping_gbp,
    airup_gmbh_sales_curr.shipping_sek,
    airup_gmbh_sales_curr.orders,
    airup_gmbh_sales_curr.return_amount,
    airup_gmbh_sales_curr.return_amount_chf,
    airup_gmbh_sales_curr.return_amount_gbp,
    airup_gmbh_sales_curr.return_amount_sek,
    airup_gmbh_sales_curr.shopify_shop,
    airup_gmbh_sales_curr.currency_abbreviation,
    airup_gmbh_sales_curr.conversion_rate_eur,
    airup_gmbh_sales_curr.customer_email,
    airup_gmbh_sales_curr.customer_name,
    airup_gmbh_sales_curr.shop_cust_id
   FROM airup_gmbh_sales_curr
UNION ALL
 SELECT airup_ch_sales_curr._fivetran_synced,
    airup_ch_sales_curr.creation_date,
    airup_ch_sales_curr.customer_id,
    airup_ch_sales_curr.created_at,
    airup_ch_sales_curr.utm_campaign_medium,
    airup_ch_sales_curr.utm_campaign_name,
    airup_ch_sales_curr.net_sales,
    airup_ch_sales_curr.net_sales_chf,
    airup_ch_sales_curr.net_sales_gbp,
    airup_ch_sales_curr.net_sales_sek,
    airup_ch_sales_curr.gross_sales,
    airup_ch_sales_curr.gross_sales_chf,
    airup_ch_sales_curr.gross_sales_gbp,
    airup_ch_sales_curr.gross_sales_sek,
    airup_ch_sales_curr.taxes,
    airup_ch_sales_curr.taxes_chf,
    airup_ch_sales_curr.taxes_gbp,
    airup_ch_sales_curr.taxes_sek,
    airup_ch_sales_curr.discounts,
    airup_ch_sales_curr.discounts_chf,
    airup_ch_sales_curr.discounts_gbp,
    airup_ch_sales_curr.discounts_sek,
    airup_ch_sales_curr.shipping,
    airup_ch_sales_curr.shipping_chf,
    airup_ch_sales_curr.shipping_gbp,
    airup_ch_sales_curr.shipping_sek,
    airup_ch_sales_curr.orders,
    airup_ch_sales_curr.return_amount,
    airup_ch_sales_curr.return_amount_chf,
    airup_ch_sales_curr.return_amount_gbp,
    airup_ch_sales_curr.return_amount_sek,
    airup_ch_sales_curr.shopify_shop,
    airup_ch_sales_curr.currency_abbreviation,
    airup_ch_sales_curr.conversion_rate_eur,
    airup_ch_sales_curr.customer_email,
    airup_ch_sales_curr.customer_name,
    airup_ch_sales_curr.shop_cust_id
   FROM airup_ch_sales_curr
UNION ALL
 SELECT airup_uk_sales_curr._fivetran_synced,
    airup_uk_sales_curr.creation_date,
    airup_uk_sales_curr.customer_id,
    airup_uk_sales_curr.created_at,
    airup_uk_sales_curr.utm_campaign_medium,
    airup_uk_sales_curr.utm_campaign_name,
    airup_uk_sales_curr.net_sales,
    airup_uk_sales_curr.net_sales_chf,
    airup_uk_sales_curr.net_sales_gbp,
    airup_uk_sales_curr.net_sales_sek,
    airup_uk_sales_curr.gross_sales,
    airup_uk_sales_curr.gross_sales_chf,
    airup_uk_sales_curr.gross_sales_gbp,
    airup_uk_sales_curr.gross_sales_sek,
    airup_uk_sales_curr.taxes,
    airup_uk_sales_curr.taxes_chf,
    airup_uk_sales_curr.taxes_gbp,
    airup_uk_sales_curr.taxes_sek,
    airup_uk_sales_curr.discounts,
    airup_uk_sales_curr.discounts_chf,
    airup_uk_sales_curr.discounts_gbp,
    airup_uk_sales_curr.discounts_sek,
    airup_uk_sales_curr.shipping,
    airup_uk_sales_curr.shipping_chf,
    airup_uk_sales_curr.shipping_gbp,
    airup_uk_sales_curr.shipping_sek,
    airup_uk_sales_curr.orders,
    airup_uk_sales_curr.return_amount,
    airup_uk_sales_curr.return_amount_chf,
    airup_uk_sales_curr.return_amount_gbp,
    airup_uk_sales_curr.return_amount_sek,
    airup_uk_sales_curr.shopify_shop,
    airup_uk_sales_curr.currency_abbreviation,
    airup_uk_sales_curr.conversion_rate_eur,
    airup_uk_sales_curr.customer_email,
    airup_uk_sales_curr.customer_name,
    airup_uk_sales_curr.shop_cust_id
   FROM airup_uk_sales_curr
UNION ALL
 SELECT airup_fr_sales_curr._fivetran_synced,
    airup_fr_sales_curr.creation_date,
    airup_fr_sales_curr.customer_id,
    airup_fr_sales_curr.created_at,
    airup_fr_sales_curr.utm_campaign_medium,
    airup_fr_sales_curr.utm_campaign_name,
    airup_fr_sales_curr.net_sales,
    airup_fr_sales_curr.net_sales_chf,
    airup_fr_sales_curr.net_sales_gbp,
    airup_fr_sales_curr.net_sales_sek,
    airup_fr_sales_curr.gross_sales,
    airup_fr_sales_curr.gross_sales_chf,
    airup_fr_sales_curr.gross_sales_gbp,
    airup_fr_sales_curr.gross_sales_sek,
    airup_fr_sales_curr.taxes,
    airup_fr_sales_curr.taxes_chf,
    airup_fr_sales_curr.taxes_gbp,
    airup_fr_sales_curr.taxes_sek,
    airup_fr_sales_curr.discounts,
    airup_fr_sales_curr.discounts_chf,
    airup_fr_sales_curr.discounts_gbp,
    airup_fr_sales_curr.discounts_sek,
    airup_fr_sales_curr.shipping,
    airup_fr_sales_curr.shipping_chf,
    airup_fr_sales_curr.shipping_gbp,
    airup_fr_sales_curr.shipping_sek,
    airup_fr_sales_curr.orders,
    airup_fr_sales_curr.return_amount,
    airup_fr_sales_curr.return_amount_chf,
    airup_fr_sales_curr.return_amount_gbp,
    airup_fr_sales_curr.return_amount_sek,
    airup_fr_sales_curr.shopify_shop,
    airup_fr_sales_curr.currency_abbreviation,
    airup_fr_sales_curr.conversion_rate_eur,
    airup_fr_sales_curr.customer_email,
    airup_fr_sales_curr.customer_name,
    airup_fr_sales_curr.shop_cust_id
   FROM airup_fr_sales_curr
UNION ALL
 SELECT airup_nl_sales_curr._fivetran_synced,
    airup_nl_sales_curr.creation_date,
    airup_nl_sales_curr.customer_id,
    airup_nl_sales_curr.created_at,
    airup_nl_sales_curr.utm_campaign_medium,
    airup_nl_sales_curr.utm_campaign_name,
    airup_nl_sales_curr.net_sales,
    airup_nl_sales_curr.net_sales_chf,
    airup_nl_sales_curr.net_sales_gbp,
    airup_nl_sales_curr.net_sales_sek,
    airup_nl_sales_curr.gross_sales,
    airup_nl_sales_curr.gross_sales_chf,
    airup_nl_sales_curr.gross_sales_gbp,
    airup_nl_sales_curr.gross_sales_sek,
    airup_nl_sales_curr.taxes,
    airup_nl_sales_curr.taxes_chf,
    airup_nl_sales_curr.taxes_gbp,
    airup_nl_sales_curr.taxes_sek,
    airup_nl_sales_curr.discounts,
    airup_nl_sales_curr.discounts_chf,
    airup_nl_sales_curr.discounts_gbp,
    airup_nl_sales_curr.discounts_sek,
    airup_nl_sales_curr.shipping,
    airup_nl_sales_curr.shipping_chf,
    airup_nl_sales_curr.shipping_gbp,
    airup_nl_sales_curr.shipping_sek,
    airup_nl_sales_curr.orders,
    airup_nl_sales_curr.return_amount,
    airup_nl_sales_curr.return_amount_chf,
    airup_nl_sales_curr.return_amount_gbp,
    airup_nl_sales_curr.return_amount_sek,
    airup_nl_sales_curr.shopify_shop,
    airup_nl_sales_curr.currency_abbreviation,
    airup_nl_sales_curr.conversion_rate_eur,
    airup_nl_sales_curr.customer_email,
    airup_nl_sales_curr.customer_name,
    airup_nl_sales_curr.shop_cust_id
   FROM airup_nl_sales_curr
UNION ALL
 SELECT airup_it_sales_curr._fivetran_synced,
    airup_it_sales_curr.creation_date,
    airup_it_sales_curr.customer_id,
    airup_it_sales_curr.created_at,
    airup_it_sales_curr.utm_campaign_medium,
    airup_it_sales_curr.utm_campaign_name,
    airup_it_sales_curr.net_sales,
    airup_it_sales_curr.net_sales_chf,
    airup_it_sales_curr.net_sales_gbp,
    airup_it_sales_curr.net_sales_sek,
    airup_it_sales_curr.gross_sales,
    airup_it_sales_curr.gross_sales_chf,
    airup_it_sales_curr.gross_sales_gbp,
    airup_it_sales_curr.gross_sales_sek,
    airup_it_sales_curr.taxes,
    airup_it_sales_curr.taxes_chf,
    airup_it_sales_curr.taxes_gbp,
    airup_it_sales_curr.taxes_sek,
    airup_it_sales_curr.discounts,
    airup_it_sales_curr.discounts_chf,
    airup_it_sales_curr.discounts_gbp,
    airup_it_sales_curr.discounts_sek,
    airup_it_sales_curr.shipping,
    airup_it_sales_curr.shipping_chf,
    airup_it_sales_curr.shipping_gbp,
    airup_it_sales_curr.shipping_sek,
    airup_it_sales_curr.orders,
    airup_it_sales_curr.return_amount,
    airup_it_sales_curr.return_amount_chf,
    airup_it_sales_curr.return_amount_gbp,
    airup_it_sales_curr.return_amount_sek,
    airup_it_sales_curr.shopify_shop,
    airup_it_sales_curr.currency_abbreviation,
    airup_it_sales_curr.conversion_rate_eur,
    airup_it_sales_curr.customer_email,
    airup_it_sales_curr.customer_name,
    airup_it_sales_curr.shop_cust_id
   FROM airup_it_sales_curr
UNION ALL
 SELECT airup_sek_sales_curr._fivetran_synced,
    airup_sek_sales_curr.creation_date,
    airup_sek_sales_curr.customer_id,
    airup_sek_sales_curr.created_at,
    airup_sek_sales_curr.utm_campaign_medium,
    airup_sek_sales_curr.utm_campaign_name,
    airup_sek_sales_curr.net_sales,
    airup_sek_sales_curr.net_sales_chf,
    airup_sek_sales_curr.net_sales_gbp,
    airup_sek_sales_curr.net_sales_sek,
    airup_sek_sales_curr.gross_sales,
    airup_sek_sales_curr.gross_sales_chf,
    airup_sek_sales_curr.gross_sales_gbp,
    airup_sek_sales_curr.gross_sales_sek,
    airup_sek_sales_curr.taxes,
    airup_sek_sales_curr.taxes_chf,
    airup_sek_sales_curr.taxes_gbp,
    airup_sek_sales_curr.taxes_sek,
    airup_sek_sales_curr.discounts,
    airup_sek_sales_curr.discounts_chf,
    airup_sek_sales_curr.discounts_gbp,
    airup_sek_sales_curr.discounts_sek,
    airup_sek_sales_curr.shipping,
    airup_sek_sales_curr.shipping_chf,
    airup_sek_sales_curr.shipping_gbp,
    airup_sek_sales_curr.shipping_sek,
    airup_sek_sales_curr.orders,
    airup_sek_sales_curr.return_amount,
    airup_sek_sales_curr.return_amount_chf,
    airup_sek_sales_curr.return_amount_gbp,
    airup_sek_sales_curr.return_amount_sek,
    airup_sek_sales_curr.shopify_shop,
    airup_sek_sales_curr.currency_abbreviation,
    airup_sek_sales_curr.conversion_rate_eur,
    airup_sek_sales_curr.customer_email,
    airup_sek_sales_curr.customer_name,
    airup_sek_sales_curr.shop_cust_id
   FROM airup_sek_sales_curr