

WITH airup_gmbh_discounts_raw AS (
         SELECT airup_gmbh_discounts._fivetran_synced,
            date(airup_gmbh_discounts._fivetran_synced) AS creation_date,
            airup_gmbh_discounts.day AS created_at,
            airup_gmbh_discounts.discount_applied,
            airup_gmbh_discounts.discount_code,
            airup_gmbh_discounts.discount_type,
            airup_gmbh_discounts.name AS discount_name,
            airup_gmbh_discounts.total_line_item_script_discount,
            NULL::double precision AS total_line_item_script_discount_chf,
            NULL::double precision AS total_line_item_script_discount_gbp,
            NULL::double precision AS total_line_item_script_discount_sek,
            airup_gmbh_discounts.total_gross_sales,
            NULL::double precision AS total_gross_sales_chf,
            NULL::double precision AS total_gross_sales_gbp,
            NULL::double precision AS total_gross_sales_sek,
            airup_gmbh_discounts.total_discount_amount,
            NULL::double precision AS total_discount_amount_chf,
            NULL::double precision AS total_discount_amount_gbp,
            NULL::double precision AS total_discount_amount_sek,
            airup_gmbh_discounts.total_returns,
            NULL::double precision AS total_returns_chf,
            NULL::double precision AS total_returns_gbp,
            NULL::double precision AS total_returns_sek,
            airup_gmbh_discounts.total_shipping_script_discount,
            NULL::double precision AS total_shipping_script_discount_chf,
            NULL::double precision AS total_shipping_script_discount_gbp,
            NULL::double precision AS total_shipping_script_discount_sek,
            airup_gmbh_discounts.total_shipping_price,
            NULL::double precision AS total_shipping_price_chf,
            NULL::double precision AS total_shipping_price_gbp,
            NULL::double precision AS total_shipping_price_sek,
            airup_gmbh_discounts.total_shipping_discount,
            NULL::double precision AS total_shipping_discount_chf,
            NULL::double precision AS total_shipping_discount_gbp,
            NULL::double precision AS total_shipping_discount_sek,
            airup_gmbh_discounts.orders,
            airup_gmbh_discounts.total_tax_amount,
            NULL::double precision AS total_tax_amount_chf,
            NULL::double precision AS total_tax_amount_gbp,
            NULL::double precision AS total_tax_amount_sek,
            airup_gmbh_discounts.grand_total_sales,
            NULL::double precision AS grand_total_sales_chf,
            NULL::double precision AS grand_total_sales_gbp,
            NULL::double precision AS grand_total_sales_sek,
            airup_gmbh_discounts.total_net_sales,
            NULL::double precision AS total_net_sales_chf,
            NULL::double precision AS total_net_sales_gbp,
            NULL::double precision AS total_net_sales_sek,
            'Base'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_gmbh_discounts.email AS customer_email,
            airup_gmbh_discounts.customer_name,
            md5(airup_gmbh_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_gmbh_discounts" airup_gmbh_discounts
        ), global_curr_eur AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'EUR'::text
        ), airup_gmbh_discounts_curr AS (
         SELECT airup_gmbh_discounts_raw._fivetran_synced,
            airup_gmbh_discounts_raw.creation_date,
            airup_gmbh_discounts_raw.created_at,
            airup_gmbh_discounts_raw.discount_applied,
            airup_gmbh_discounts_raw.discount_code,
            airup_gmbh_discounts_raw.discount_type,
            airup_gmbh_discounts_raw.discount_name,
            airup_gmbh_discounts_raw.total_line_item_script_discount,
            airup_gmbh_discounts_raw.total_line_item_script_discount_chf,
            airup_gmbh_discounts_raw.total_line_item_script_discount_gbp,
            airup_gmbh_discounts_raw.total_line_item_script_discount_sek,
            airup_gmbh_discounts_raw.total_gross_sales,
            airup_gmbh_discounts_raw.total_gross_sales_chf,
            airup_gmbh_discounts_raw.total_gross_sales_gbp,
            airup_gmbh_discounts_raw.total_gross_sales_sek,
            airup_gmbh_discounts_raw.total_discount_amount,
            airup_gmbh_discounts_raw.total_discount_amount_chf,
            airup_gmbh_discounts_raw.total_discount_amount_gbp,
            airup_gmbh_discounts_raw.total_discount_amount_sek,
            airup_gmbh_discounts_raw.total_returns,
            airup_gmbh_discounts_raw.total_returns_chf,
            airup_gmbh_discounts_raw.total_returns_gbp,
            airup_gmbh_discounts_raw.total_returns_sek,
            airup_gmbh_discounts_raw.total_shipping_script_discount,
            airup_gmbh_discounts_raw.total_shipping_script_discount_chf,
            airup_gmbh_discounts_raw.total_shipping_script_discount_gbp,
            airup_gmbh_discounts_raw.total_shipping_script_discount_sek,
            airup_gmbh_discounts_raw.total_shipping_price,
            airup_gmbh_discounts_raw.total_shipping_price_chf,
            airup_gmbh_discounts_raw.total_shipping_price_gbp,
            airup_gmbh_discounts_raw.total_shipping_price_sek,
            airup_gmbh_discounts_raw.total_shipping_discount,
            airup_gmbh_discounts_raw.total_shipping_discount_chf,
            airup_gmbh_discounts_raw.total_shipping_discount_gbp,
            airup_gmbh_discounts_raw.total_shipping_discount_sek,
            airup_gmbh_discounts_raw.orders,
            airup_gmbh_discounts_raw.total_tax_amount,
            airup_gmbh_discounts_raw.total_tax_amount_chf,
            airup_gmbh_discounts_raw.total_tax_amount_gbp,
            airup_gmbh_discounts_raw.total_tax_amount_sek,
            airup_gmbh_discounts_raw.grand_total_sales,
            airup_gmbh_discounts_raw.grand_total_sales_chf,
            airup_gmbh_discounts_raw.grand_total_sales_gbp,
            airup_gmbh_discounts_raw.grand_total_sales_sek,
            airup_gmbh_discounts_raw.total_net_sales,
            airup_gmbh_discounts_raw.total_net_sales_chf,
            airup_gmbh_discounts_raw.total_net_sales_gbp,
            airup_gmbh_discounts_raw.total_net_sales_sek,
            airup_gmbh_discounts_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_gmbh_discounts_raw.customer_email,
            airup_gmbh_discounts_raw.customer_name,
            airup_gmbh_discounts_raw.customer_id
           FROM airup_gmbh_discounts_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_ch_discounts_raw AS (
         SELECT airup_ch_discounts._fivetran_synced,
            date(airup_ch_discounts._fivetran_synced) AS creation_date,
            airup_ch_discounts.day AS created_at,
            airup_ch_discounts.discount_applied,
            airup_ch_discounts.discount_code,
            airup_ch_discounts.discount_type,
            airup_ch_discounts.name AS discount_name,
            airup_ch_discounts.total_line_item_script_discount,
            airup_ch_discounts.total_line_item_script_discount AS total_line_item_script_discount_chf,
            NULL::double precision AS total_line_item_script_discount_gbp,
            NULL::double precision AS total_line_item_script_discount_sek,
            airup_ch_discounts.total_gross_sales,
            airup_ch_discounts.total_gross_sales AS total_gross_sales_chf,
            NULL::double precision AS total_gross_sales_gbp,
            NULL::double precision AS total_gross_sales_sek,
            airup_ch_discounts.total_discount_amount,
            airup_ch_discounts.total_discount_amount AS total_discount_amount_chf,
            NULL::double precision AS total_discount_amount_gbp,
            NULL::double precision AS total_discount_amount_sek,
            airup_ch_discounts.total_returns,
            airup_ch_discounts.total_returns AS total_returns_chf,
            NULL::double precision AS total_returns_gbp,
            NULL::double precision AS total_returns_sek,
            airup_ch_discounts.total_shipping_script_discount,
            airup_ch_discounts.total_shipping_script_discount AS total_shipping_script_discount_chf,
            NULL::double precision AS total_shipping_script_discount_gbp,
            NULL::double precision AS total_shipping_script_discount_sek,
            airup_ch_discounts.total_shipping_price,
            airup_ch_discounts.total_shipping_price AS total_shipping_price_chf,
            NULL::double precision AS total_shipping_price_gbp,
            NULL::double precision AS total_shipping_price_sek,
            airup_ch_discounts.total_shipping_discount,
            airup_ch_discounts.total_shipping_discount AS total_shipping_discount_chf,
            NULL::double precision AS total_shipping_discount_gbp,
            NULL::double precision AS total_shipping_discount_sek,
            airup_ch_discounts.orders,
            airup_ch_discounts.total_tax_amount,
            airup_ch_discounts.total_tax_amount AS total_tax_amount_chf,
            NULL::double precision AS total_tax_amount_gbp,
            NULL::double precision AS total_tax_amount_sek,
            airup_ch_discounts.grand_total_sales,
            airup_ch_discounts.grand_total_sales AS grand_total_sales_chf,
            NULL::double precision AS grand_total_sales_gbp,
            NULL::double precision AS grand_total_sales_sek,
            airup_ch_discounts.total_net_sales,
            airup_ch_discounts.total_net_sales AS total_net_sales_chf,
            NULL::double precision AS total_net_sales_gbp,
            NULL::double precision AS total_net_sales_sek,
            'CH'::text AS shopify_shop,
            'CHF'::text AS currency_abbreviation,
            airup_ch_discounts.email AS customer_email,
            airup_ch_discounts.customer_name,
            md5(airup_ch_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_ch_discounts" airup_ch_discounts
        ), global_curr_chf AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'CHF'::text
        ), airup_ch_discounts_curr AS (
         SELECT airup_ch_discounts_raw._fivetran_synced,
            airup_ch_discounts_raw.creation_date,
            airup_ch_discounts_raw.created_at,
            airup_ch_discounts_raw.discount_applied,
            airup_ch_discounts_raw.discount_code,
            airup_ch_discounts_raw.discount_type,
            airup_ch_discounts_raw.discount_name,
            (airup_ch_discounts_raw.total_line_item_script_discount /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_line_item_script_discount,
            airup_ch_discounts_raw.total_line_item_script_discount_chf,
            airup_ch_discounts_raw.total_line_item_script_discount_gbp,
            airup_ch_discounts_raw.total_line_item_script_discount_sek,
            (airup_ch_discounts_raw.total_gross_sales /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_gross_sales,
            airup_ch_discounts_raw.total_gross_sales_chf,
            airup_ch_discounts_raw.total_gross_sales_gbp,
            airup_ch_discounts_raw.total_gross_sales_sek,
            (airup_ch_discounts_raw.total_discount_amount /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_discount_amount,
            airup_ch_discounts_raw.total_discount_amount_chf,
            airup_ch_discounts_raw.total_discount_amount_gbp,
            airup_ch_discounts_raw.total_discount_amount_sek,
            (airup_ch_discounts_raw.total_returns /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_returns,
            airup_ch_discounts_raw.total_returns_chf,
            airup_ch_discounts_raw.total_returns_gbp,
            airup_ch_discounts_raw.total_returns_sek,
            (airup_ch_discounts_raw.total_shipping_script_discount /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_shipping_script_discount,
            airup_ch_discounts_raw.total_shipping_script_discount_chf,
            airup_ch_discounts_raw.total_shipping_script_discount_gbp,
            airup_ch_discounts_raw.total_shipping_script_discount_sek,
            (airup_ch_discounts_raw.total_shipping_price /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_shipping_price,
            airup_ch_discounts_raw.total_shipping_price_chf,
            airup_ch_discounts_raw.total_shipping_price_gbp,
            airup_ch_discounts_raw.total_shipping_price_sek,
            (airup_ch_discounts_raw.total_shipping_discount /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_shipping_discount,
            airup_ch_discounts_raw.total_shipping_discount_chf,
            airup_ch_discounts_raw.total_shipping_discount_gbp,
            airup_ch_discounts_raw.total_shipping_discount_sek,
            airup_ch_discounts_raw.orders,
            (airup_ch_discounts_raw.total_tax_amount /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_tax_amount,
            airup_ch_discounts_raw.total_tax_amount_chf,
            airup_ch_discounts_raw.total_tax_amount_gbp,
            airup_ch_discounts_raw.total_tax_amount_sek,
            (airup_ch_discounts_raw.grand_total_sales /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS grand_total_sales,
            airup_ch_discounts_raw.grand_total_sales_chf,
            airup_ch_discounts_raw.grand_total_sales_gbp,
            airup_ch_discounts_raw.grand_total_sales_sek,
            (airup_ch_discounts_raw.total_net_sales /
                CASE
                    WHEN global_curr_chf.conversion_rate_eur IS NOT NULL THEN global_curr_chf.conversion_rate_eur
                    ELSE 1.0986::double precision
                END)::numeric(10,3)::double precision AS total_net_sales,
            airup_ch_discounts_raw.total_net_sales_chf,
            airup_ch_discounts_raw.total_net_sales_gbp,
            airup_ch_discounts_raw.total_net_sales_sek,
            airup_ch_discounts_raw.shopify_shop,
            global_curr_chf.currency_abbreviation,
            global_curr_chf.conversion_rate_eur,
            airup_ch_discounts_raw.customer_email,
            airup_ch_discounts_raw.customer_name,
            airup_ch_discounts_raw.customer_id
           FROM airup_ch_discounts_raw
             LEFT JOIN global_curr_chf USING (currency_abbreviation, creation_date)
        ), airup_gbp_discounts_raw AS (
         SELECT airup_uk_discounts._fivetran_synced,
            date(airup_uk_discounts._fivetran_synced) AS creation_date,
            airup_uk_discounts.day AS created_at,
            airup_uk_discounts.discount_applied,
            airup_uk_discounts.discount_code,
            airup_uk_discounts.discount_type,
            airup_uk_discounts.name AS discount_name,
            airup_uk_discounts.total_line_item_script_discount,
            NULL::double precision AS total_line_item_script_discount_chf,
            airup_uk_discounts.total_line_item_script_discount AS total_line_item_script_discount_gbp,
            NULL::double precision AS total_line_item_script_discount_sek,
            airup_uk_discounts.total_gross_sales,
            NULL::double precision AS total_gross_sales_chf,
            airup_uk_discounts.total_gross_sales AS total_gross_sales_gbp,
            NULL::double precision AS total_gross_sales_sek,
            airup_uk_discounts.total_discount_amount,
            NULL::double precision AS total_discount_amount_chf,
            airup_uk_discounts.total_discount_amount AS total_discount_amount_gbp,
            NULL::double precision AS total_discount_amount_sek,
            airup_uk_discounts.total_returns,
            NULL::double precision AS total_returns_chf,
            airup_uk_discounts.total_returns AS total_returns_gbp,
            NULL::double precision AS total_returns_sek,
            airup_uk_discounts.total_shipping_script_discount,
            NULL::double precision AS total_shipping_script_discount_chf,
            airup_uk_discounts.total_shipping_script_discount AS total_shipping_script_discount_gbp,
            NULL::double precision AS total_shipping_script_discount_sek,
            airup_uk_discounts.total_shipping_price,
            NULL::double precision AS total_shipping_price_chf,
            airup_uk_discounts.total_shipping_price AS total_shipping_price_gbp,
            NULL::double precision AS total_shipping_price_sek,
            airup_uk_discounts.total_shipping_discount,
            NULL::double precision AS total_shipping_discount_chf,
            airup_uk_discounts.total_shipping_discount AS total_shipping_discount_gbp,
            NULL::double precision AS total_shipping_discount_sek,
            airup_uk_discounts.orders,
            airup_uk_discounts.total_tax_amount,
            NULL::double precision AS total_tax_amount_chf,
            airup_uk_discounts.total_tax_amount AS total_tax_amount_gbp,
            NULL::double precision AS total_tax_amount_sek,
            airup_uk_discounts.grand_total_sales,
            NULL::double precision AS grand_total_sales_chf,
            airup_uk_discounts.grand_total_sales AS grand_total_sales_gbp,
            NULL::double precision AS grand_total_sales_sek,
            airup_uk_discounts.total_net_sales,
            NULL::double precision AS total_net_sales_chf,
            airup_uk_discounts.total_net_sales AS total_net_sales_gbp,
            NULL::double precision AS total_net_sales_sek,
            'UK'::text AS shopify_shop,
            'GBP'::text AS currency_abbreviation,
            airup_uk_discounts.email AS customer_email,
            airup_uk_discounts.customer_name,
            md5(airup_uk_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_uk_discounts" airup_uk_discounts
        ), global_curr_gbp AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'GBP'::text
        ), airup_gbp_discounts_curr AS (
         SELECT airup_gbp_discounts_raw._fivetran_synced,
            airup_gbp_discounts_raw.creation_date,
            airup_gbp_discounts_raw.created_at,
            airup_gbp_discounts_raw.discount_applied,
            airup_gbp_discounts_raw.discount_code,
            airup_gbp_discounts_raw.discount_type,
            airup_gbp_discounts_raw.discount_name,
            (airup_gbp_discounts_raw.total_line_item_script_discount /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_line_item_script_discount,
            airup_gbp_discounts_raw.total_line_item_script_discount_chf,
            airup_gbp_discounts_raw.total_line_item_script_discount_gbp,
            airup_gbp_discounts_raw.total_line_item_script_discount_sek,
            (airup_gbp_discounts_raw.total_gross_sales /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_gross_sales,
            airup_gbp_discounts_raw.total_gross_sales_chf,
            airup_gbp_discounts_raw.total_gross_sales_gbp,
            airup_gbp_discounts_raw.total_gross_sales_sek,
            (airup_gbp_discounts_raw.total_discount_amount /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_discount_amount,
            airup_gbp_discounts_raw.total_discount_amount_chf,
            airup_gbp_discounts_raw.total_discount_amount_gbp,
            airup_gbp_discounts_raw.total_discount_amount_sek,
            (airup_gbp_discounts_raw.total_returns /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_returns,
            airup_gbp_discounts_raw.total_returns_chf,
            airup_gbp_discounts_raw.total_returns_gbp,
            airup_gbp_discounts_raw.total_returns_sek,
            (airup_gbp_discounts_raw.total_shipping_script_discount /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_shipping_script_discount,
            airup_gbp_discounts_raw.total_shipping_script_discount_chf,
            airup_gbp_discounts_raw.total_shipping_script_discount_gbp,
            airup_gbp_discounts_raw.total_shipping_script_discount_sek,
            (airup_gbp_discounts_raw.total_shipping_price /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_shipping_price,
            airup_gbp_discounts_raw.total_shipping_price_chf,
            airup_gbp_discounts_raw.total_shipping_price_gbp,
            airup_gbp_discounts_raw.total_shipping_price_sek,
            (airup_gbp_discounts_raw.total_shipping_discount /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_shipping_discount,
            airup_gbp_discounts_raw.total_shipping_discount_chf,
            airup_gbp_discounts_raw.total_shipping_discount_gbp,
            airup_gbp_discounts_raw.total_shipping_discount_sek,
            airup_gbp_discounts_raw.orders,
            (airup_gbp_discounts_raw.total_tax_amount /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_tax_amount,
            airup_gbp_discounts_raw.total_tax_amount_chf,
            airup_gbp_discounts_raw.total_tax_amount_gbp,
            airup_gbp_discounts_raw.total_tax_amount_sek,
            (airup_gbp_discounts_raw.grand_total_sales /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS grand_total_sales,
            airup_gbp_discounts_raw.grand_total_sales_chf,
            airup_gbp_discounts_raw.grand_total_sales_gbp,
            airup_gbp_discounts_raw.grand_total_sales_sek,
            (airup_gbp_discounts_raw.total_net_sales /
                CASE
                    WHEN global_curr_gbp.conversion_rate_eur IS NOT NULL THEN global_curr_gbp.conversion_rate_eur
                    ELSE 0.863::double precision
                END)::numeric(10,3)::double precision AS total_net_sales,
            airup_gbp_discounts_raw.total_net_sales_chf,
            airup_gbp_discounts_raw.total_net_sales_gbp,
            airup_gbp_discounts_raw.total_net_sales_sek,
            airup_gbp_discounts_raw.shopify_shop,
            global_curr_gbp.currency_abbreviation,
            global_curr_gbp.conversion_rate_eur,
            airup_gbp_discounts_raw.customer_email,
            airup_gbp_discounts_raw.customer_name,
            airup_gbp_discounts_raw.customer_id
           FROM airup_gbp_discounts_raw
             LEFT JOIN global_curr_gbp USING (currency_abbreviation, creation_date)
        ), airup_fr_discounts_raw AS (
         SELECT airup_fr_discounts._fivetran_synced,
            date(airup_fr_discounts._fivetran_synced) AS creation_date,
            airup_fr_discounts.day AS created_at,
            airup_fr_discounts.discount_applied,
            airup_fr_discounts.discount_code,
            airup_fr_discounts.discount_type,
            airup_fr_discounts.name AS discount_name,
            airup_fr_discounts.total_line_item_script_discount,
            NULL::double precision AS total_line_item_script_discount_chf,
            NULL::double precision AS total_line_item_script_discount_gbp,
            NULL::double precision AS total_line_item_script_discount_sek,
            airup_fr_discounts.total_gross_sales,
            NULL::double precision AS total_gross_sales_chf,
            NULL::double precision AS total_gross_sales_gbp,
            NULL::double precision AS total_gross_sales_sek,
            airup_fr_discounts.total_discount_amount,
            NULL::double precision AS total_discount_amount_chf,
            NULL::double precision AS total_discount_amount_gbp,
            NULL::double precision AS total_discount_amount_sek,
            airup_fr_discounts.total_returns,
            NULL::double precision AS total_returns_chf,
            NULL::double precision AS total_returns_gbp,
            NULL::double precision AS total_returns_sek,
            airup_fr_discounts.total_shipping_script_discount,
            NULL::double precision AS total_shipping_script_discount_chf,
            NULL::double precision AS total_shipping_script_discount_gbp,
            NULL::double precision AS total_shipping_script_discount_sek,
            airup_fr_discounts.total_shipping_price,
            NULL::double precision AS total_shipping_price_chf,
            NULL::double precision AS total_shipping_price_gbp,
            NULL::double precision AS total_shipping_price_sek,
            airup_fr_discounts.total_shipping_discount,
            NULL::double precision AS total_shipping_discount_chf,
            NULL::double precision AS total_shipping_discount_gbp,
            NULL::double precision AS total_shipping_discount_sek,
            airup_fr_discounts.orders,
            airup_fr_discounts.total_tax_amount,
            NULL::double precision AS total_tax_amount_chf,
            NULL::double precision AS total_tax_amount_gbp,
            NULL::double precision AS total_tax_amount_sek,
            airup_fr_discounts.grand_total_sales,
            NULL::double precision AS grand_total_sales_chf,
            NULL::double precision AS grand_total_sales_gbp,
            NULL::double precision AS grand_total_sales_sek,
            airup_fr_discounts.total_net_sales,
            NULL::double precision AS total_net_sales_chf,
            NULL::double precision AS total_net_sales_gbp,
            NULL::double precision AS total_net_sales_sek,
            'FR'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_fr_discounts.email AS customer_email,
            airup_fr_discounts.customer_name,
            md5(airup_fr_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_fr_discounts" airup_fr_discounts
        ), airup_fr_discounts_curr AS (
         SELECT airup_fr_discounts_raw._fivetran_synced,
            airup_fr_discounts_raw.creation_date,
            airup_fr_discounts_raw.created_at,
            airup_fr_discounts_raw.discount_applied,
            airup_fr_discounts_raw.discount_code,
            airup_fr_discounts_raw.discount_type,
            airup_fr_discounts_raw.discount_name,
            airup_fr_discounts_raw.total_line_item_script_discount,
            airup_fr_discounts_raw.total_line_item_script_discount_chf,
            airup_fr_discounts_raw.total_line_item_script_discount_gbp,
            airup_fr_discounts_raw.total_line_item_script_discount_sek,
            airup_fr_discounts_raw.total_gross_sales,
            airup_fr_discounts_raw.total_gross_sales_chf,
            airup_fr_discounts_raw.total_gross_sales_gbp,
            airup_fr_discounts_raw.total_gross_sales_sek,
            airup_fr_discounts_raw.total_discount_amount,
            airup_fr_discounts_raw.total_discount_amount_chf,
            airup_fr_discounts_raw.total_discount_amount_gbp,
            airup_fr_discounts_raw.total_discount_amount_sek,
            airup_fr_discounts_raw.total_returns,
            airup_fr_discounts_raw.total_returns_chf,
            airup_fr_discounts_raw.total_returns_gbp,
            airup_fr_discounts_raw.total_returns_sek,
            airup_fr_discounts_raw.total_shipping_script_discount,
            airup_fr_discounts_raw.total_shipping_script_discount_chf,
            airup_fr_discounts_raw.total_shipping_script_discount_gbp,
            airup_fr_discounts_raw.total_shipping_script_discount_sek,
            airup_fr_discounts_raw.total_shipping_price,
            airup_fr_discounts_raw.total_shipping_price_chf,
            airup_fr_discounts_raw.total_shipping_price_gbp,
            airup_fr_discounts_raw.total_shipping_price_sek,
            airup_fr_discounts_raw.total_shipping_discount,
            airup_fr_discounts_raw.total_shipping_discount_chf,
            airup_fr_discounts_raw.total_shipping_discount_gbp,
            airup_fr_discounts_raw.total_shipping_discount_sek,
            airup_fr_discounts_raw.orders,
            airup_fr_discounts_raw.total_tax_amount,
            airup_fr_discounts_raw.total_tax_amount_chf,
            airup_fr_discounts_raw.total_tax_amount_gbp,
            airup_fr_discounts_raw.total_tax_amount_sek,
            airup_fr_discounts_raw.grand_total_sales,
            airup_fr_discounts_raw.grand_total_sales_chf,
            airup_fr_discounts_raw.grand_total_sales_gbp,
            airup_fr_discounts_raw.grand_total_sales_sek,
            airup_fr_discounts_raw.total_net_sales,
            airup_fr_discounts_raw.total_net_sales_chf,
            airup_fr_discounts_raw.total_net_sales_gbp,
            airup_fr_discounts_raw.total_net_sales_sek,
            airup_fr_discounts_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_fr_discounts_raw.customer_email,
            airup_fr_discounts_raw.customer_name,
            airup_fr_discounts_raw.customer_id
           FROM airup_fr_discounts_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_nl_discounts_raw AS (
         SELECT airup_nl_discounts._fivetran_synced,
            date(airup_nl_discounts._fivetran_synced) AS creation_date,
            airup_nl_discounts.day AS created_at,
            airup_nl_discounts.discount_applied,
            airup_nl_discounts.discount_code,
            airup_nl_discounts.discount_type,
            airup_nl_discounts.name AS discount_name,
            airup_nl_discounts.total_line_item_script_discount,
            NULL::double precision AS total_line_item_script_discount_chf,
            NULL::double precision AS total_line_item_script_discount_gbp,
            NULL::double precision AS total_line_item_script_discount_sek,
            airup_nl_discounts.total_gross_sales,
            NULL::double precision AS total_gross_sales_chf,
            NULL::double precision AS total_gross_sales_gbp,
            NULL::double precision AS total_gross_sales_sek,
            airup_nl_discounts.total_discount_amount,
            NULL::double precision AS total_discount_amount_chf,
            NULL::double precision AS total_discount_amount_gbp,
            NULL::double precision AS total_discount_amount_sek,
            airup_nl_discounts.total_returns,
            NULL::double precision AS total_returns_chf,
            NULL::double precision AS total_returns_gbp,
            NULL::double precision AS total_returns_sek,
            airup_nl_discounts.total_shipping_script_discount,
            NULL::double precision AS total_shipping_script_discount_chf,
            NULL::double precision AS total_shipping_script_discount_gbp,
            NULL::double precision AS total_shipping_script_discount_sek,
            airup_nl_discounts.total_shipping_price,
            NULL::double precision AS total_shipping_price_chf,
            NULL::double precision AS total_shipping_price_gbp,
            NULL::double precision AS total_shipping_price_sek,
            airup_nl_discounts.total_shipping_discount,
            NULL::double precision AS total_shipping_discount_chf,
            NULL::double precision AS total_shipping_discount_gbp,
            NULL::double precision AS total_shipping_discount_sek,
            airup_nl_discounts.orders,
            airup_nl_discounts.total_tax_amount,
            NULL::double precision AS total_tax_amount_chf,
            NULL::double precision AS total_tax_amount_gbp,
            NULL::double precision AS total_tax_amount_sek,
            airup_nl_discounts.grand_total_sales,
            NULL::double precision AS grand_total_sales_chf,
            NULL::double precision AS grand_total_sales_gbp,
            NULL::double precision AS grand_total_sales_sek,
            airup_nl_discounts.total_net_sales,
            NULL::double precision AS total_net_sales_chf,
            NULL::double precision AS total_net_sales_gbp,
            NULL::double precision AS total_net_sales_sek,
            'NL'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_nl_discounts.email AS customer_email,
            airup_nl_discounts.customer_name,
            md5(airup_nl_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_nl_discounts" airup_nl_discounts
        ), airup_nl_discounts_curr AS (
         SELECT airup_nl_discounts_raw._fivetran_synced,
            airup_nl_discounts_raw.creation_date,
            airup_nl_discounts_raw.created_at,
            airup_nl_discounts_raw.discount_applied,
            airup_nl_discounts_raw.discount_code,
            airup_nl_discounts_raw.discount_type,
            airup_nl_discounts_raw.discount_name,
            airup_nl_discounts_raw.total_line_item_script_discount,
            airup_nl_discounts_raw.total_line_item_script_discount_chf,
            airup_nl_discounts_raw.total_line_item_script_discount_gbp,
            airup_nl_discounts_raw.total_line_item_script_discount_sek,
            airup_nl_discounts_raw.total_gross_sales,
            airup_nl_discounts_raw.total_gross_sales_chf,
            airup_nl_discounts_raw.total_gross_sales_gbp,
            airup_nl_discounts_raw.total_gross_sales_sek,
            airup_nl_discounts_raw.total_discount_amount,
            airup_nl_discounts_raw.total_discount_amount_chf,
            airup_nl_discounts_raw.total_discount_amount_gbp,
            airup_nl_discounts_raw.total_discount_amount_sek,
            airup_nl_discounts_raw.total_returns,
            airup_nl_discounts_raw.total_returns_chf,
            airup_nl_discounts_raw.total_returns_gbp,
            airup_nl_discounts_raw.total_returns_sek,
            airup_nl_discounts_raw.total_shipping_script_discount,
            airup_nl_discounts_raw.total_shipping_script_discount_chf,
            airup_nl_discounts_raw.total_shipping_script_discount_gbp,
            airup_nl_discounts_raw.total_shipping_script_discount_sek,
            airup_nl_discounts_raw.total_shipping_price,
            airup_nl_discounts_raw.total_shipping_price_chf,
            airup_nl_discounts_raw.total_shipping_price_gbp,
            airup_nl_discounts_raw.total_shipping_price_sek,
            airup_nl_discounts_raw.total_shipping_discount,
            airup_nl_discounts_raw.total_shipping_discount_chf,
            airup_nl_discounts_raw.total_shipping_discount_gbp,
            airup_nl_discounts_raw.total_shipping_discount_sek,
            airup_nl_discounts_raw.orders,
            airup_nl_discounts_raw.total_tax_amount,
            airup_nl_discounts_raw.total_tax_amount_chf,
            airup_nl_discounts_raw.total_tax_amount_gbp,
            airup_nl_discounts_raw.total_tax_amount_sek,
            airup_nl_discounts_raw.grand_total_sales,
            airup_nl_discounts_raw.grand_total_sales_chf,
            airup_nl_discounts_raw.grand_total_sales_gbp,
            airup_nl_discounts_raw.grand_total_sales_sek,
            airup_nl_discounts_raw.total_net_sales,
            airup_nl_discounts_raw.total_net_sales_chf,
            airup_nl_discounts_raw.total_net_sales_gbp,
            airup_nl_discounts_raw.total_net_sales_sek,
            airup_nl_discounts_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_nl_discounts_raw.customer_email,
            airup_nl_discounts_raw.customer_name,
            airup_nl_discounts_raw.customer_id
           FROM airup_nl_discounts_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_it_discounts_raw AS (
         SELECT airup_it_discounts._fivetran_synced,
            date(airup_it_discounts._fivetran_synced) AS creation_date,
            airup_it_discounts.day AS created_at,
            airup_it_discounts.discount_applied,
            airup_it_discounts.discount_code,
            airup_it_discounts.discount_type,
            airup_it_discounts.name AS discount_name,
            airup_it_discounts.total_line_item_script_discount,
            NULL::double precision AS total_line_item_script_discount_chf,
            NULL::double precision AS total_line_item_script_discount_gbp,
            NULL::double precision AS total_line_item_script_discount_sek,
            airup_it_discounts.total_gross_sales,
            NULL::double precision AS total_gross_sales_chf,
            NULL::double precision AS total_gross_sales_gbp,
            NULL::double precision AS total_gross_sales_sek,
            airup_it_discounts.total_discount_amount,
            NULL::double precision AS total_discount_amount_chf,
            NULL::double precision AS total_discount_amount_gbp,
            NULL::double precision AS total_discount_amount_sek,
            airup_it_discounts.total_returns,
            NULL::double precision AS total_returns_chf,
            NULL::double precision AS total_returns_gbp,
            NULL::double precision AS total_returns_sek,
            airup_it_discounts.total_shipping_script_discount,
            NULL::double precision AS total_shipping_script_discount_chf,
            NULL::double precision AS total_shipping_script_discount_gbp,
            NULL::double precision AS total_shipping_script_discount_sek,
            airup_it_discounts.total_shipping_price,
            NULL::double precision AS total_shipping_price_chf,
            NULL::double precision AS total_shipping_price_gbp,
            NULL::double precision AS total_shipping_price_sek,
            airup_it_discounts.total_shipping_discount,
            NULL::double precision AS total_shipping_discount_chf,
            NULL::double precision AS total_shipping_discount_gbp,
            NULL::double precision AS total_shipping_discount_sek,
            airup_it_discounts.orders,
            airup_it_discounts.total_tax_amount,
            NULL::double precision AS total_tax_amount_chf,
            NULL::double precision AS total_tax_amount_gbp,
            NULL::double precision AS total_tax_amount_sek,
            airup_it_discounts.grand_total_sales,
            NULL::double precision AS grand_total_sales_chf,
            NULL::double precision AS grand_total_sales_gbp,
            NULL::double precision AS grand_total_sales_sek,
            airup_it_discounts.total_net_sales,
            NULL::double precision AS total_net_sales_chf,
            NULL::double precision AS total_net_sales_gbp,
            NULL::double precision AS total_net_sales_sek,
            'IT'::text AS shopify_shop,
            'EUR'::text AS currency_abbreviation,
            airup_it_discounts.email AS customer_email,
            airup_it_discounts.customer_name,
            md5(airup_it_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_it_discounts" airup_it_discounts
        ), airup_it_discounts_curr AS (
         SELECT airup_it_discounts_raw._fivetran_synced,
            airup_it_discounts_raw.creation_date,
            airup_it_discounts_raw.created_at,
            airup_it_discounts_raw.discount_applied,
            airup_it_discounts_raw.discount_code,
            airup_it_discounts_raw.discount_type,
            airup_it_discounts_raw.discount_name,
            airup_it_discounts_raw.total_line_item_script_discount,
            airup_it_discounts_raw.total_line_item_script_discount_chf,
            airup_it_discounts_raw.total_line_item_script_discount_gbp,
            airup_it_discounts_raw.total_line_item_script_discount_sek,
            airup_it_discounts_raw.total_gross_sales,
            airup_it_discounts_raw.total_gross_sales_chf,
            airup_it_discounts_raw.total_gross_sales_gbp,
            airup_it_discounts_raw.total_gross_sales_sek,
            airup_it_discounts_raw.total_discount_amount,
            airup_it_discounts_raw.total_discount_amount_chf,
            airup_it_discounts_raw.total_discount_amount_gbp,
            airup_it_discounts_raw.total_discount_amount_sek,
            airup_it_discounts_raw.total_returns,
            airup_it_discounts_raw.total_returns_chf,
            airup_it_discounts_raw.total_returns_gbp,
            airup_it_discounts_raw.total_returns_sek,
            airup_it_discounts_raw.total_shipping_script_discount,
            airup_it_discounts_raw.total_shipping_script_discount_chf,
            airup_it_discounts_raw.total_shipping_script_discount_gbp,
            airup_it_discounts_raw.total_shipping_script_discount_sek,
            airup_it_discounts_raw.total_shipping_price,
            airup_it_discounts_raw.total_shipping_price_chf,
            airup_it_discounts_raw.total_shipping_price_gbp,
            airup_it_discounts_raw.total_shipping_price_sek,
            airup_it_discounts_raw.total_shipping_discount,
            airup_it_discounts_raw.total_shipping_discount_chf,
            airup_it_discounts_raw.total_shipping_discount_gbp,
            airup_it_discounts_raw.total_shipping_discount_sek,
            airup_it_discounts_raw.orders,
            airup_it_discounts_raw.total_tax_amount,
            airup_it_discounts_raw.total_tax_amount_chf,
            airup_it_discounts_raw.total_tax_amount_gbp,
            airup_it_discounts_raw.total_tax_amount_sek,
            airup_it_discounts_raw.grand_total_sales,
            airup_it_discounts_raw.grand_total_sales_chf,
            airup_it_discounts_raw.grand_total_sales_gbp,
            airup_it_discounts_raw.grand_total_sales_sek,
            airup_it_discounts_raw.total_net_sales,
            airup_it_discounts_raw.total_net_sales_chf,
            airup_it_discounts_raw.total_net_sales_gbp,
            airup_it_discounts_raw.total_net_sales_sek,
            airup_it_discounts_raw.shopify_shop,
            global_curr_eur.currency_abbreviation,
            global_curr_eur.conversion_rate_eur,
            airup_it_discounts_raw.customer_email,
            airup_it_discounts_raw.customer_name,
            airup_it_discounts_raw.customer_id
           FROM airup_it_discounts_raw
             LEFT JOIN global_curr_eur USING (currency_abbreviation, creation_date)
        ), airup_sek_discounts_raw AS (
         SELECT airup_se_discounts._fivetran_synced,
            date(airup_se_discounts._fivetran_synced) AS creation_date,
            airup_se_discounts.day AS created_at,
            airup_se_discounts.discount_applied,
            airup_se_discounts.discount_code,
            airup_se_discounts.discount_type,
            airup_se_discounts.name AS discount_name,
            airup_se_discounts.total_line_item_script_discount,
            NULL::double precision AS total_line_item_script_discount_chf,
            NULL::double precision AS total_line_item_script_discount_gbp,
            airup_se_discounts.total_line_item_script_discount AS total_line_item_script_discount_sek,
            airup_se_discounts.total_gross_sales,
            NULL::double precision AS total_gross_sales_chf,
            NULL::double precision AS total_gross_sales_gbp,
            airup_se_discounts.total_gross_sales AS total_gross_sales_sek,
            airup_se_discounts.total_discount_amount,
            NULL::double precision AS total_discount_amount_chf,
            NULL::double precision AS total_discount_amount_gbp,
            airup_se_discounts.total_discount_amount AS total_discount_amount_sek,
            airup_se_discounts.total_returns,
            NULL::double precision AS total_returns_chf,
            NULL::double precision AS total_returns_gbp,
            airup_se_discounts.total_returns AS total_returns_sek,
            airup_se_discounts.total_shipping_script_discount,
            NULL::double precision AS total_shipping_script_discount_chf,
            NULL::double precision AS total_shipping_script_discount_gbp,
            airup_se_discounts.total_shipping_script_discount AS total_shipping_script_discount_sek,
            airup_se_discounts.total_shipping_price,
            NULL::double precision AS total_shipping_price_chf,
            NULL::double precision AS total_shipping_price_gbp,
            airup_se_discounts.total_shipping_price AS total_shipping_price_sek,
            airup_se_discounts.total_shipping_discount,
            NULL::double precision AS total_shipping_discount_chf,
            NULL::double precision AS total_shipping_discount_gbp,
            airup_se_discounts.total_shipping_discount AS total_shipping_discount_sek,
            airup_se_discounts.orders,
            airup_se_discounts.total_tax_amount,
            NULL::double precision AS total_tax_amount_chf,
            NULL::double precision AS total_tax_amount_gbp,
            airup_se_discounts.total_tax_amount AS total_tax_amount_sek,
            airup_se_discounts.grand_total_sales,
            NULL::double precision AS grand_total_sales_chf,
            NULL::double precision AS grand_total_sales_gbp,
            airup_se_discounts.grand_total_sales AS grand_total_sales_sek,
            airup_se_discounts.total_net_sales,
            NULL::double precision AS total_net_sales_chf,
            NULL::double precision AS total_net_sales_gbp,
            airup_se_discounts.total_net_sales AS total_net_sales_sek,
            'SE'::text AS shopify_shop,
            'SEK'::text AS currency_abbreviation,
            airup_se_discounts.email AS customer_email,
            airup_se_discounts.customer_name,
            md5(airup_se_discounts.email::text) AS customer_id
           FROM "airup_eu_dwh"."shopify_influencer_analytics"."airup_se_discounts" airup_se_discounts
        ), global_curr_sek AS (
         SELECT date(global_currency_rates.creation_datetime) AS creation_date,
            global_currency_rates.currency_abbreviation,
            global_currency_rates.conversion_rate_eur
           FROM "airup_eu_dwh"."odoo_currency"."dim_global_currency_rates" global_currency_rates
          WHERE global_currency_rates.currency_abbreviation::text = 'SEK'::text
        ), airup_sek_discounts_curr AS (
         SELECT airup_sek_discounts_raw._fivetran_synced,
            airup_sek_discounts_raw.creation_date,
            airup_sek_discounts_raw.created_at,
            airup_sek_discounts_raw.discount_applied,
            airup_sek_discounts_raw.discount_code,
            airup_sek_discounts_raw.discount_type,
            airup_sek_discounts_raw.discount_name,
            (airup_sek_discounts_raw.total_line_item_script_discount /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_line_item_script_discount,
            airup_sek_discounts_raw.total_line_item_script_discount_chf,
            airup_sek_discounts_raw.total_line_item_script_discount_gbp,
            airup_sek_discounts_raw.total_line_item_script_discount_sek,
            (airup_sek_discounts_raw.total_gross_sales /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_gross_sales,
            airup_sek_discounts_raw.total_gross_sales_chf,
            airup_sek_discounts_raw.total_gross_sales_gbp,
            airup_sek_discounts_raw.total_gross_sales_sek,
            (airup_sek_discounts_raw.total_discount_amount /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_discount_amount,
            airup_sek_discounts_raw.total_discount_amount_chf,
            airup_sek_discounts_raw.total_discount_amount_gbp,
            airup_sek_discounts_raw.total_discount_amount_sek,
            (airup_sek_discounts_raw.total_returns /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_returns,
            airup_sek_discounts_raw.total_returns_chf,
            airup_sek_discounts_raw.total_returns_gbp,
            airup_sek_discounts_raw.total_returns_sek,
            (airup_sek_discounts_raw.total_shipping_script_discount /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_shipping_script_discount,
            airup_sek_discounts_raw.total_shipping_script_discount_chf,
            airup_sek_discounts_raw.total_shipping_script_discount_gbp,
            airup_sek_discounts_raw.total_shipping_script_discount_sek,
            (airup_sek_discounts_raw.total_shipping_price /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_shipping_price,
            airup_sek_discounts_raw.total_shipping_price_chf,
            airup_sek_discounts_raw.total_shipping_price_gbp,
            airup_sek_discounts_raw.total_shipping_price_sek,
            (airup_sek_discounts_raw.total_shipping_discount /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_shipping_discount,
            airup_sek_discounts_raw.total_shipping_discount_chf,
            airup_sek_discounts_raw.total_shipping_discount_gbp,
            airup_sek_discounts_raw.total_shipping_discount_sek,
            airup_sek_discounts_raw.orders,
            (airup_sek_discounts_raw.total_tax_amount /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_tax_amount,
            airup_sek_discounts_raw.total_tax_amount_chf,
            airup_sek_discounts_raw.total_tax_amount_gbp,
            airup_sek_discounts_raw.total_tax_amount_sek,
            (airup_sek_discounts_raw.grand_total_sales /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS grand_total_sales,
            airup_sek_discounts_raw.grand_total_sales_chf,
            airup_sek_discounts_raw.grand_total_sales_gbp,
            airup_sek_discounts_raw.grand_total_sales_sek,
            (airup_sek_discounts_raw.total_net_sales /
                CASE
                    WHEN global_curr_sek.conversion_rate_eur IS NOT NULL THEN global_curr_sek.conversion_rate_eur
                    ELSE 10.69::double precision
                END)::numeric(10,3)::double precision AS total_net_sales,
            airup_sek_discounts_raw.total_net_sales_chf,
            airup_sek_discounts_raw.total_net_sales_gbp,
            airup_sek_discounts_raw.total_net_sales_sek,
            airup_sek_discounts_raw.shopify_shop,
            global_curr_sek.currency_abbreviation,
            global_curr_sek.conversion_rate_eur,
            airup_sek_discounts_raw.customer_email,
            airup_sek_discounts_raw.customer_name,
            airup_sek_discounts_raw.customer_id
           FROM airup_sek_discounts_raw
             LEFT JOIN global_curr_sek USING (currency_abbreviation, creation_date)
        )
 SELECT airup_gmbh_discounts_curr._fivetran_synced,
    airup_gmbh_discounts_curr.creation_date,
    airup_gmbh_discounts_curr.created_at,
    airup_gmbh_discounts_curr.discount_applied,
    airup_gmbh_discounts_curr.discount_code,
    airup_gmbh_discounts_curr.discount_type,
    airup_gmbh_discounts_curr.discount_name,
    airup_gmbh_discounts_curr.total_line_item_script_discount,
    airup_gmbh_discounts_curr.total_line_item_script_discount_chf,
    airup_gmbh_discounts_curr.total_line_item_script_discount_gbp,
    airup_gmbh_discounts_curr.total_line_item_script_discount_sek,
    airup_gmbh_discounts_curr.total_gross_sales,
    airup_gmbh_discounts_curr.total_gross_sales_chf,
    airup_gmbh_discounts_curr.total_gross_sales_gbp,
    airup_gmbh_discounts_curr.total_gross_sales_sek,
    airup_gmbh_discounts_curr.total_discount_amount,
    airup_gmbh_discounts_curr.total_discount_amount_chf,
    airup_gmbh_discounts_curr.total_discount_amount_gbp,
    airup_gmbh_discounts_curr.total_discount_amount_sek,
    airup_gmbh_discounts_curr.total_returns,
    airup_gmbh_discounts_curr.total_returns_chf,
    airup_gmbh_discounts_curr.total_returns_gbp,
    airup_gmbh_discounts_curr.total_returns_sek,
    airup_gmbh_discounts_curr.total_shipping_script_discount,
    airup_gmbh_discounts_curr.total_shipping_script_discount_chf,
    airup_gmbh_discounts_curr.total_shipping_script_discount_gbp,
    airup_gmbh_discounts_curr.total_shipping_script_discount_sek,
    airup_gmbh_discounts_curr.total_shipping_price,
    airup_gmbh_discounts_curr.total_shipping_price_chf,
    airup_gmbh_discounts_curr.total_shipping_price_gbp,
    airup_gmbh_discounts_curr.total_shipping_price_sek,
    airup_gmbh_discounts_curr.total_shipping_discount,
    airup_gmbh_discounts_curr.total_shipping_discount_chf,
    airup_gmbh_discounts_curr.total_shipping_discount_gbp,
    airup_gmbh_discounts_curr.total_shipping_discount_sek,
    airup_gmbh_discounts_curr.orders,
    airup_gmbh_discounts_curr.total_tax_amount,
    airup_gmbh_discounts_curr.total_tax_amount_chf,
    airup_gmbh_discounts_curr.total_tax_amount_gbp,
    airup_gmbh_discounts_curr.total_tax_amount_sek,
    airup_gmbh_discounts_curr.grand_total_sales,
    airup_gmbh_discounts_curr.grand_total_sales_chf,
    airup_gmbh_discounts_curr.grand_total_sales_gbp,
    airup_gmbh_discounts_curr.grand_total_sales_sek,
    airup_gmbh_discounts_curr.total_net_sales,
    airup_gmbh_discounts_curr.total_net_sales_chf,
    airup_gmbh_discounts_curr.total_net_sales_gbp,
    airup_gmbh_discounts_curr.total_net_sales_sek,
    airup_gmbh_discounts_curr.shopify_shop,
    airup_gmbh_discounts_curr.currency_abbreviation,
    airup_gmbh_discounts_curr.conversion_rate_eur,
    airup_gmbh_discounts_curr.customer_email,
    airup_gmbh_discounts_curr.customer_name,
    airup_gmbh_discounts_curr.customer_id
   FROM airup_gmbh_discounts_curr
UNION ALL
 SELECT airup_ch_discounts_curr._fivetran_synced,
    airup_ch_discounts_curr.creation_date,
    airup_ch_discounts_curr.created_at,
    airup_ch_discounts_curr.discount_applied,
    airup_ch_discounts_curr.discount_code,
    airup_ch_discounts_curr.discount_type,
    airup_ch_discounts_curr.discount_name,
    airup_ch_discounts_curr.total_line_item_script_discount,
    airup_ch_discounts_curr.total_line_item_script_discount_chf,
    airup_ch_discounts_curr.total_line_item_script_discount_gbp,
    airup_ch_discounts_curr.total_line_item_script_discount_sek,
    airup_ch_discounts_curr.total_gross_sales,
    airup_ch_discounts_curr.total_gross_sales_chf,
    airup_ch_discounts_curr.total_gross_sales_gbp,
    airup_ch_discounts_curr.total_gross_sales_sek,
    airup_ch_discounts_curr.total_discount_amount,
    airup_ch_discounts_curr.total_discount_amount_chf,
    airup_ch_discounts_curr.total_discount_amount_gbp,
    airup_ch_discounts_curr.total_discount_amount_sek,
    airup_ch_discounts_curr.total_returns,
    airup_ch_discounts_curr.total_returns_chf,
    airup_ch_discounts_curr.total_returns_gbp,
    airup_ch_discounts_curr.total_returns_sek,
    airup_ch_discounts_curr.total_shipping_script_discount,
    airup_ch_discounts_curr.total_shipping_script_discount_chf,
    airup_ch_discounts_curr.total_shipping_script_discount_gbp,
    airup_ch_discounts_curr.total_shipping_script_discount_sek,
    airup_ch_discounts_curr.total_shipping_price,
    airup_ch_discounts_curr.total_shipping_price_chf,
    airup_ch_discounts_curr.total_shipping_price_gbp,
    airup_ch_discounts_curr.total_shipping_price_sek,
    airup_ch_discounts_curr.total_shipping_discount,
    airup_ch_discounts_curr.total_shipping_discount_chf,
    airup_ch_discounts_curr.total_shipping_discount_gbp,
    airup_ch_discounts_curr.total_shipping_discount_sek,
    airup_ch_discounts_curr.orders,
    airup_ch_discounts_curr.total_tax_amount,
    airup_ch_discounts_curr.total_tax_amount_chf,
    airup_ch_discounts_curr.total_tax_amount_gbp,
    airup_ch_discounts_curr.total_tax_amount_sek,
    airup_ch_discounts_curr.grand_total_sales,
    airup_ch_discounts_curr.grand_total_sales_chf,
    airup_ch_discounts_curr.grand_total_sales_gbp,
    airup_ch_discounts_curr.grand_total_sales_sek,
    airup_ch_discounts_curr.total_net_sales,
    airup_ch_discounts_curr.total_net_sales_chf,
    airup_ch_discounts_curr.total_net_sales_gbp,
    airup_ch_discounts_curr.total_net_sales_sek,
    airup_ch_discounts_curr.shopify_shop,
    airup_ch_discounts_curr.currency_abbreviation,
    airup_ch_discounts_curr.conversion_rate_eur,
    airup_ch_discounts_curr.customer_email,
    airup_ch_discounts_curr.customer_name,
    airup_ch_discounts_curr.customer_id
   FROM airup_ch_discounts_curr
UNION ALL
 SELECT airup_gbp_discounts_curr._fivetran_synced,
    airup_gbp_discounts_curr.creation_date,
    airup_gbp_discounts_curr.created_at,
    airup_gbp_discounts_curr.discount_applied,
    airup_gbp_discounts_curr.discount_code,
    airup_gbp_discounts_curr.discount_type,
    airup_gbp_discounts_curr.discount_name,
    airup_gbp_discounts_curr.total_line_item_script_discount,
    airup_gbp_discounts_curr.total_line_item_script_discount_chf,
    airup_gbp_discounts_curr.total_line_item_script_discount_gbp,
    airup_gbp_discounts_curr.total_line_item_script_discount_sek,
    airup_gbp_discounts_curr.total_gross_sales,
    airup_gbp_discounts_curr.total_gross_sales_chf,
    airup_gbp_discounts_curr.total_gross_sales_gbp,
    airup_gbp_discounts_curr.total_gross_sales_sek,
    airup_gbp_discounts_curr.total_discount_amount,
    airup_gbp_discounts_curr.total_discount_amount_chf,
    airup_gbp_discounts_curr.total_discount_amount_gbp,
    airup_gbp_discounts_curr.total_discount_amount_sek,
    airup_gbp_discounts_curr.total_returns,
    airup_gbp_discounts_curr.total_returns_chf,
    airup_gbp_discounts_curr.total_returns_gbp,
    airup_gbp_discounts_curr.total_returns_sek,
    airup_gbp_discounts_curr.total_shipping_script_discount,
    airup_gbp_discounts_curr.total_shipping_script_discount_chf,
    airup_gbp_discounts_curr.total_shipping_script_discount_gbp,
    airup_gbp_discounts_curr.total_shipping_script_discount_sek,
    airup_gbp_discounts_curr.total_shipping_price,
    airup_gbp_discounts_curr.total_shipping_price_chf,
    airup_gbp_discounts_curr.total_shipping_price_gbp,
    airup_gbp_discounts_curr.total_shipping_price_sek,
    airup_gbp_discounts_curr.total_shipping_discount,
    airup_gbp_discounts_curr.total_shipping_discount_chf,
    airup_gbp_discounts_curr.total_shipping_discount_gbp,
    airup_gbp_discounts_curr.total_shipping_discount_sek,
    airup_gbp_discounts_curr.orders,
    airup_gbp_discounts_curr.total_tax_amount,
    airup_gbp_discounts_curr.total_tax_amount_chf,
    airup_gbp_discounts_curr.total_tax_amount_gbp,
    airup_gbp_discounts_curr.total_tax_amount_sek,
    airup_gbp_discounts_curr.grand_total_sales,
    airup_gbp_discounts_curr.grand_total_sales_chf,
    airup_gbp_discounts_curr.grand_total_sales_gbp,
    airup_gbp_discounts_curr.grand_total_sales_sek,
    airup_gbp_discounts_curr.total_net_sales,
    airup_gbp_discounts_curr.total_net_sales_chf,
    airup_gbp_discounts_curr.total_net_sales_gbp,
    airup_gbp_discounts_curr.total_net_sales_sek,
    airup_gbp_discounts_curr.shopify_shop,
    airup_gbp_discounts_curr.currency_abbreviation,
    airup_gbp_discounts_curr.conversion_rate_eur,
    airup_gbp_discounts_curr.customer_email,
    airup_gbp_discounts_curr.customer_name,
    airup_gbp_discounts_curr.customer_id
   FROM airup_gbp_discounts_curr
UNION ALL
 SELECT airup_fr_discounts_curr._fivetran_synced,
    airup_fr_discounts_curr.creation_date,
    airup_fr_discounts_curr.created_at,
    airup_fr_discounts_curr.discount_applied,
    airup_fr_discounts_curr.discount_code,
    airup_fr_discounts_curr.discount_type,
    airup_fr_discounts_curr.discount_name,
    airup_fr_discounts_curr.total_line_item_script_discount,
    airup_fr_discounts_curr.total_line_item_script_discount_chf,
    airup_fr_discounts_curr.total_line_item_script_discount_gbp,
    airup_fr_discounts_curr.total_line_item_script_discount_sek,
    airup_fr_discounts_curr.total_gross_sales,
    airup_fr_discounts_curr.total_gross_sales_chf,
    airup_fr_discounts_curr.total_gross_sales_gbp,
    airup_fr_discounts_curr.total_gross_sales_sek,
    airup_fr_discounts_curr.total_discount_amount,
    airup_fr_discounts_curr.total_discount_amount_chf,
    airup_fr_discounts_curr.total_discount_amount_gbp,
    airup_fr_discounts_curr.total_discount_amount_sek,
    airup_fr_discounts_curr.total_returns,
    airup_fr_discounts_curr.total_returns_chf,
    airup_fr_discounts_curr.total_returns_gbp,
    airup_fr_discounts_curr.total_returns_sek,
    airup_fr_discounts_curr.total_shipping_script_discount,
    airup_fr_discounts_curr.total_shipping_script_discount_chf,
    airup_fr_discounts_curr.total_shipping_script_discount_gbp,
    airup_fr_discounts_curr.total_shipping_script_discount_sek,
    airup_fr_discounts_curr.total_shipping_price,
    airup_fr_discounts_curr.total_shipping_price_chf,
    airup_fr_discounts_curr.total_shipping_price_gbp,
    airup_fr_discounts_curr.total_shipping_price_sek,
    airup_fr_discounts_curr.total_shipping_discount,
    airup_fr_discounts_curr.total_shipping_discount_chf,
    airup_fr_discounts_curr.total_shipping_discount_gbp,
    airup_fr_discounts_curr.total_shipping_discount_sek,
    airup_fr_discounts_curr.orders,
    airup_fr_discounts_curr.total_tax_amount,
    airup_fr_discounts_curr.total_tax_amount_chf,
    airup_fr_discounts_curr.total_tax_amount_gbp,
    airup_fr_discounts_curr.total_tax_amount_sek,
    airup_fr_discounts_curr.grand_total_sales,
    airup_fr_discounts_curr.grand_total_sales_chf,
    airup_fr_discounts_curr.grand_total_sales_gbp,
    airup_fr_discounts_curr.grand_total_sales_sek,
    airup_fr_discounts_curr.total_net_sales,
    airup_fr_discounts_curr.total_net_sales_chf,
    airup_fr_discounts_curr.total_net_sales_gbp,
    airup_fr_discounts_curr.total_net_sales_sek,
    airup_fr_discounts_curr.shopify_shop,
    airup_fr_discounts_curr.currency_abbreviation,
    airup_fr_discounts_curr.conversion_rate_eur,
    airup_fr_discounts_curr.customer_email,
    airup_fr_discounts_curr.customer_name,
    airup_fr_discounts_curr.customer_id
   FROM airup_fr_discounts_curr
UNION ALL
 SELECT airup_nl_discounts_curr._fivetran_synced,
    airup_nl_discounts_curr.creation_date,
    airup_nl_discounts_curr.created_at,
    airup_nl_discounts_curr.discount_applied,
    airup_nl_discounts_curr.discount_code,
    airup_nl_discounts_curr.discount_type,
    airup_nl_discounts_curr.discount_name,
    airup_nl_discounts_curr.total_line_item_script_discount,
    airup_nl_discounts_curr.total_line_item_script_discount_chf,
    airup_nl_discounts_curr.total_line_item_script_discount_gbp,
    airup_nl_discounts_curr.total_line_item_script_discount_sek,
    airup_nl_discounts_curr.total_gross_sales,
    airup_nl_discounts_curr.total_gross_sales_chf,
    airup_nl_discounts_curr.total_gross_sales_gbp,
    airup_nl_discounts_curr.total_gross_sales_sek,
    airup_nl_discounts_curr.total_discount_amount,
    airup_nl_discounts_curr.total_discount_amount_chf,
    airup_nl_discounts_curr.total_discount_amount_gbp,
    airup_nl_discounts_curr.total_discount_amount_sek,
    airup_nl_discounts_curr.total_returns,
    airup_nl_discounts_curr.total_returns_chf,
    airup_nl_discounts_curr.total_returns_gbp,
    airup_nl_discounts_curr.total_returns_sek,
    airup_nl_discounts_curr.total_shipping_script_discount,
    airup_nl_discounts_curr.total_shipping_script_discount_chf,
    airup_nl_discounts_curr.total_shipping_script_discount_gbp,
    airup_nl_discounts_curr.total_shipping_script_discount_sek,
    airup_nl_discounts_curr.total_shipping_price,
    airup_nl_discounts_curr.total_shipping_price_chf,
    airup_nl_discounts_curr.total_shipping_price_gbp,
    airup_nl_discounts_curr.total_shipping_price_sek,
    airup_nl_discounts_curr.total_shipping_discount,
    airup_nl_discounts_curr.total_shipping_discount_chf,
    airup_nl_discounts_curr.total_shipping_discount_gbp,
    airup_nl_discounts_curr.total_shipping_discount_sek,
    airup_nl_discounts_curr.orders,
    airup_nl_discounts_curr.total_tax_amount,
    airup_nl_discounts_curr.total_tax_amount_chf,
    airup_nl_discounts_curr.total_tax_amount_gbp,
    airup_nl_discounts_curr.total_tax_amount_sek,
    airup_nl_discounts_curr.grand_total_sales,
    airup_nl_discounts_curr.grand_total_sales_chf,
    airup_nl_discounts_curr.grand_total_sales_gbp,
    airup_nl_discounts_curr.grand_total_sales_sek,
    airup_nl_discounts_curr.total_net_sales,
    airup_nl_discounts_curr.total_net_sales_chf,
    airup_nl_discounts_curr.total_net_sales_gbp,
    airup_nl_discounts_curr.total_net_sales_sek,
    airup_nl_discounts_curr.shopify_shop,
    airup_nl_discounts_curr.currency_abbreviation,
    airup_nl_discounts_curr.conversion_rate_eur,
    airup_nl_discounts_curr.customer_email,
    airup_nl_discounts_curr.customer_name,
    airup_nl_discounts_curr.customer_id
   FROM airup_nl_discounts_curr
UNION ALL
 SELECT airup_it_discounts_curr._fivetran_synced,
    airup_it_discounts_curr.creation_date,
    airup_it_discounts_curr.created_at,
    airup_it_discounts_curr.discount_applied,
    airup_it_discounts_curr.discount_code,
    airup_it_discounts_curr.discount_type,
    airup_it_discounts_curr.discount_name,
    airup_it_discounts_curr.total_line_item_script_discount,
    airup_it_discounts_curr.total_line_item_script_discount_chf,
    airup_it_discounts_curr.total_line_item_script_discount_gbp,
    airup_it_discounts_curr.total_line_item_script_discount_sek,
    airup_it_discounts_curr.total_gross_sales,
    airup_it_discounts_curr.total_gross_sales_chf,
    airup_it_discounts_curr.total_gross_sales_gbp,
    airup_it_discounts_curr.total_gross_sales_sek,
    airup_it_discounts_curr.total_discount_amount,
    airup_it_discounts_curr.total_discount_amount_chf,
    airup_it_discounts_curr.total_discount_amount_gbp,
    airup_it_discounts_curr.total_discount_amount_sek,
    airup_it_discounts_curr.total_returns,
    airup_it_discounts_curr.total_returns_chf,
    airup_it_discounts_curr.total_returns_gbp,
    airup_it_discounts_curr.total_returns_sek,
    airup_it_discounts_curr.total_shipping_script_discount,
    airup_it_discounts_curr.total_shipping_script_discount_chf,
    airup_it_discounts_curr.total_shipping_script_discount_gbp,
    airup_it_discounts_curr.total_shipping_script_discount_sek,
    airup_it_discounts_curr.total_shipping_price,
    airup_it_discounts_curr.total_shipping_price_chf,
    airup_it_discounts_curr.total_shipping_price_gbp,
    airup_it_discounts_curr.total_shipping_price_sek,
    airup_it_discounts_curr.total_shipping_discount,
    airup_it_discounts_curr.total_shipping_discount_chf,
    airup_it_discounts_curr.total_shipping_discount_gbp,
    airup_it_discounts_curr.total_shipping_discount_sek,
    airup_it_discounts_curr.orders,
    airup_it_discounts_curr.total_tax_amount,
    airup_it_discounts_curr.total_tax_amount_chf,
    airup_it_discounts_curr.total_tax_amount_gbp,
    airup_it_discounts_curr.total_tax_amount_sek,
    airup_it_discounts_curr.grand_total_sales,
    airup_it_discounts_curr.grand_total_sales_chf,
    airup_it_discounts_curr.grand_total_sales_gbp,
    airup_it_discounts_curr.grand_total_sales_sek,
    airup_it_discounts_curr.total_net_sales,
    airup_it_discounts_curr.total_net_sales_chf,
    airup_it_discounts_curr.total_net_sales_gbp,
    airup_it_discounts_curr.total_net_sales_sek,
    airup_it_discounts_curr.shopify_shop,
    airup_it_discounts_curr.currency_abbreviation,
    airup_it_discounts_curr.conversion_rate_eur,
    airup_it_discounts_curr.customer_email,
    airup_it_discounts_curr.customer_name,
    airup_it_discounts_curr.customer_id
   FROM airup_it_discounts_curr
UNION ALL
 SELECT airup_sek_discounts_curr._fivetran_synced,
    airup_sek_discounts_curr.creation_date,
    airup_sek_discounts_curr.created_at,
    airup_sek_discounts_curr.discount_applied,
    airup_sek_discounts_curr.discount_code,
    airup_sek_discounts_curr.discount_type,
    airup_sek_discounts_curr.discount_name,
    airup_sek_discounts_curr.total_line_item_script_discount,
    airup_sek_discounts_curr.total_line_item_script_discount_chf,
    airup_sek_discounts_curr.total_line_item_script_discount_gbp,
    airup_sek_discounts_curr.total_line_item_script_discount_sek,
    airup_sek_discounts_curr.total_gross_sales,
    airup_sek_discounts_curr.total_gross_sales_chf,
    airup_sek_discounts_curr.total_gross_sales_gbp,
    airup_sek_discounts_curr.total_gross_sales_sek,
    airup_sek_discounts_curr.total_discount_amount,
    airup_sek_discounts_curr.total_discount_amount_chf,
    airup_sek_discounts_curr.total_discount_amount_gbp,
    airup_sek_discounts_curr.total_discount_amount_sek,
    airup_sek_discounts_curr.total_returns,
    airup_sek_discounts_curr.total_returns_chf,
    airup_sek_discounts_curr.total_returns_gbp,
    airup_sek_discounts_curr.total_returns_sek,
    airup_sek_discounts_curr.total_shipping_script_discount,
    airup_sek_discounts_curr.total_shipping_script_discount_chf,
    airup_sek_discounts_curr.total_shipping_script_discount_gbp,
    airup_sek_discounts_curr.total_shipping_script_discount_sek,
    airup_sek_discounts_curr.total_shipping_price,
    airup_sek_discounts_curr.total_shipping_price_chf,
    airup_sek_discounts_curr.total_shipping_price_gbp,
    airup_sek_discounts_curr.total_shipping_price_sek,
    airup_sek_discounts_curr.total_shipping_discount,
    airup_sek_discounts_curr.total_shipping_discount_chf,
    airup_sek_discounts_curr.total_shipping_discount_gbp,
    airup_sek_discounts_curr.total_shipping_discount_sek,
    airup_sek_discounts_curr.orders,
    airup_sek_discounts_curr.total_tax_amount,
    airup_sek_discounts_curr.total_tax_amount_chf,
    airup_sek_discounts_curr.total_tax_amount_gbp,
    airup_sek_discounts_curr.total_tax_amount_sek,
    airup_sek_discounts_curr.grand_total_sales,
    airup_sek_discounts_curr.grand_total_sales_chf,
    airup_sek_discounts_curr.grand_total_sales_gbp,
    airup_sek_discounts_curr.grand_total_sales_sek,
    airup_sek_discounts_curr.total_net_sales,
    airup_sek_discounts_curr.total_net_sales_chf,
    airup_sek_discounts_curr.total_net_sales_gbp,
    airup_sek_discounts_curr.total_net_sales_sek,
    airup_sek_discounts_curr.shopify_shop,
    airup_sek_discounts_curr.currency_abbreviation,
    airup_sek_discounts_curr.conversion_rate_eur,
    airup_sek_discounts_curr.customer_email,
    airup_sek_discounts_curr.customer_name,
    airup_sek_discounts_curr.customer_id
   FROM airup_sek_discounts_curr