 

SELECT fct_mws_cohort_proc_sep_initial_purchase_by_country.country_abbreviation,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.country_fullname,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.cohort,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.date_diff_months,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.init_order_incl_starter_set,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.init_order_incl_pods,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.net_revenue,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.avg_pod_items_per_customer,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.avg_pod_orders_per_customer,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.nr_of_customers,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.avg_order_date_diff_days,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.pod_orders_per_customer,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.returning_customers_cohort,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.returning_customers_pods_first_cohort,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_with_pods,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_with_loops,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_pods_first,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_with_pods_or_loops,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_with_pods_pods_first,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_with_loops_pods_first,
       fct_mws_cohort_proc_sep_initial_purchase_by_country.subsequent_orders_with_pods_or_loops_pods_first
FROM "airup_eu_dwh"."amazon"."fct_mws_cohort_proc_sep_initial_purchase_by_country"
UNION ALL
SELECT 'all'::character varying AS country_abbreviation,
       'all'::character varying AS country_fullname,
       fct_mws_cohort_proc_sep_initial_purchase_global.cohort,
       fct_mws_cohort_proc_sep_initial_purchase_global.date_diff_months,
       fct_mws_cohort_proc_sep_initial_purchase_global.init_order_incl_starter_set,
       fct_mws_cohort_proc_sep_initial_purchase_global.init_order_incl_pods,
       fct_mws_cohort_proc_sep_initial_purchase_global.net_revenue,
       fct_mws_cohort_proc_sep_initial_purchase_global.avg_pod_items_per_customer,
       fct_mws_cohort_proc_sep_initial_purchase_global.avg_pod_orders_per_customer,
       fct_mws_cohort_proc_sep_initial_purchase_global.nr_of_customers,
       fct_mws_cohort_proc_sep_initial_purchase_global.avg_order_date_diff_days,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders,
       fct_mws_cohort_proc_sep_initial_purchase_global.pod_orders_per_customer,
       fct_mws_cohort_proc_sep_initial_purchase_global.returning_customers_cohort,
       fct_mws_cohort_proc_sep_initial_purchase_global.returning_customers_pods_first_cohort,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_with_pods,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_with_loops,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_pods_first,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_with_pods_or_loops,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_with_pods_pods_first,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_with_loops_pods_first,
       fct_mws_cohort_proc_sep_initial_purchase_global.subsequent_orders_with_pods_or_loops_pods_first
FROM "airup_eu_dwh"."amazon"."fct_mws_cohort_proc_sep_initial_purchase_global"